import { describe, expect, it } from 'vitest'

import { deriveFounderOperatingView } from './attention-operating-view'

describe('founder operating view', () => {
  it('projects compact evidence without granting execution authority', () => {
    const generatedAt = new Date('2026-08-22T20:00:00.000Z')
    const result = deriveFounderOperatingView({
      generatedAt,
      briefing: {
        schemaVersion: 2,
        focus: {
          kind: 'APPROVAL',
          urgency: 'HIGH',
          label: 'Founder decision',
          title: 'Approve customer lifecycle change',
          detail: 'One bounded approval request is waiting.',
          action: {
            label: 'Make a decision',
            href: '/admin/operations#approval-attention-heading',
          },
          source: {
            scope: 'TENANT',
            objectType: 'approval-request',
            objectId: 'approval_1',
            tenantId: 'tenant_1',
            venueId: 'venue_1',
          },
          decisionContext: {
            attentionReason:
              'A proposed action is waiting for an explicit human approval decision.',
            consequence:
              'The proposed action remains unexecuted until a human decision is recorded.',
            observedAt: new Date('2026-08-25T11:00:00.000Z'),
            deadline: null,
            occurrenceCount: 1,
            founderResponseRequiredToProceed: true,
          },
        },
        metrics: {
          decisions: 1,
          criticalRisks: 0,
          workingAgents: 2,
          customerItems: 0,
          actionItems: 1,
        },
        boundedSnapshot: { limit: 10, hasMore: false },
        reviewState: {
          lastReviewedThrough: null,
          changesSinceLastReview: {
            criticalRisks: 0,
            decisions: 1,
            completedAgents: 0,
            outcomes: 1,
            customerItems: 0,
            attentionItems: 1,
          },
          changeDigest: { limit: 5, visibleCount: 0, mayHaveMore: false, items: [] },
          hasUnreviewedChanges: true,
        },
      },
      agentTrustEvidence: {
        schemaVersion: 3,
        state: 'NEGATIVE_EVIDENCE_PRESENT',
        verdicts: { positive: 1, mixed: 0, negative: 1, inconclusive: 0 },
        observations: 2,
        distinctObservedRuns: 2,
        completedRuns: { visible: 2, withObservation: 2, withoutObservation: 0 },
        runs: { visible: 2, completed: 2, failed: 0 },
        actions: { visible: 2, succeeded: 2, failed: 0, denied: 0, cancelled: 0 },
        approvalDecisions: {
          visible: 1,
          approved: 1,
          rejected: 0,
          cancelled: 0,
          expired: 0,
          acceptance: { numerator: 1, denominator: 1, rate: 1, excludes: ['CANCELLED', 'EXPIRED'] },
        },
        qualityEvaluations: { positive: 0, mixed: 0, negative: 1, inconclusive: 0 },
        customerSignals: { positive: 0, mixed: 0, negative: 0, inconclusive: 0 },
        rollbackEvidence: {
          observations: 0,
          distinctActions: 0,
          succeededActionDenominator: 2,
          rate: 0,
          completeWindow: true,
        },
        policyViolationEvidence: {
          observations: 0,
          low: 0,
          medium: 0,
          high: 0,
          critical: 0,
          policyCodes: [],
        },
        confidenceCalibration: {
          observations: 0,
          correct: 0,
          incorrect: 0,
          meanPredictedConfidence: null,
          observedAccuracy: null,
          brierScore: null,
          completeWindow: true,
        },
        taskClasses: ['support'],
        signalKinds: ['HUMAN_REVIEW'],
        byAgent: [],
        evidenceCoverage: {
          executionRuns: 'AVAILABLE',
          explicitOutcomes: 'AVAILABLE',
          toolActions: 'AVAILABLE',
          approvalAcceptance: 'AVAILABLE',
          deniedActions: 'AVAILABLE_NOT_POLICY_VIOLATION',
          rollbackRate: 'AVAILABLE_COMPLETE_WINDOW',
          policyViolations: 'AVAILABLE_CANONICAL_SIGNAL',
          confidenceCalibration: 'AVAILABLE_CANONICAL_PREDICTION_OUTCOME_PAIR',
        },
        boundedSnapshot: { hasMore: false },
        policy: {
          approvalReductionRecommended: false,
          explanation: 'Negative evidence is present.',
        },
      },
      unitEconomics: {
        schemaVersion: 'founder-unit-economics.v1',
        generatedAt,
        window: {
          days: 30,
          start: new Date('2026-07-23T20:00:00.000Z'),
          endExclusive: generatedAt,
          previousStart: new Date('2026-06-23T20:00:00.000Z'),
        },
        totals: {
          knownOperatingCostUsd: '12.00000000',
          priorKnownOperatingCostUsd: '10.00000000',
          changeUsd: '2.00000000',
          changePercent: 20,
        },
        ai: {
          estimatedCostUsd: '12.00000000',
          requestCount: 4,
          attributedTenantCount: 1,
          completeness: 'PROVIDER_PRICING_ESTIMATE',
        },
        nonAi: {
          evidencedCostUsd: '0.00000000',
          platformUnallocatedUsd: '0.00000000',
          tenantOrVenueAttributedUsd: '0.00000000',
          evidenceCount: 0,
          excludedOverlappingEvidenceCount: 0,
          categories: [],
        },
        operationalUsage: {
          interpretation: 'Latest measured quantities are not provider invoices or dollar costs.',
          rowsReturned: 0,
          truncated: false,
          freshness: { declaredUsageDays: 2, queueUsageMinutes: 60 },
          metrics: [
            {
              metric: 'INTAKE_DECLARED_BYTES',
              represented: false,
              quantity: '0',
              unit: null,
              scopeCount: 0,
              latestObservedAt: null,
              sourceSystems: [],
            },
            {
              metric: 'MEDIA_DECLARED_BYTES',
              represented: false,
              quantity: '0',
              unit: null,
              scopeCount: 0,
              latestObservedAt: null,
              sourceSystems: [],
            },
            {
              metric: 'QUEUE_DEPTH',
              represented: false,
              quantity: '0',
              unit: null,
              scopeCount: 0,
              latestObservedAt: null,
              sourceSystems: [],
            },
            {
              metric: 'QUEUE_FAILED_JOBS',
              represented: false,
              quantity: '0',
              unit: null,
              scopeCount: 0,
              latestObservedAt: null,
              sourceSystems: [],
            },
            {
              metric: 'QUEUE_OLDEST_AGE_MILLISECONDS',
              represented: false,
              quantity: '0',
              unit: null,
              scopeCount: 0,
              latestObservedAt: null,
              sourceSystems: [],
            },
          ],
          representedMetrics: [],
          unrepresentedMetrics: [
            'INTAKE_DECLARED_BYTES',
            'MEDIA_DECLARED_BYTES',
            'QUEUE_DEPTH',
            'QUEUE_FAILED_JOBS',
            'QUEUE_OLDEST_AGE_MILLISECONDS',
          ],
          assignsDollarValue: false,
          definesAnomalyThreshold: false,
        },
        coverage: {
          representedCategories: [],
          unrepresentedCategories: [
            'STORAGE',
            'EMAIL',
            'MEDIA_PROCESSING',
            'INFRASTRUCTURE',
            'OBSERVABILITY',
            'SECURITY',
            'BANDWIDTH',
            'OPERATOR_TIME',
            'OTHER',
          ],
          complete: false,
          interpretation: 'Only contained evidence is summed.',
        },
        policy: {
          anomalyThreshold: 'UNRESOLVED',
          anomalyClassification: 'NOT_COMPUTED',
          affectsInvoices: false,
          affectsCustomerPricing: false,
          authorizesServiceCutoff: false,
        },
      },
      founderConversation: [],
    })

    expect(result).toMatchObject({
      schemaVersion: 2,
      generatedAt,
      scope: 'PLATFORM',
      effect: 'READ_ONLY',
      focus: { kind: 'APPROVAL', source: { objectId: 'approval_1' } },
      autonomyEvidence: {
        state: 'NEGATIVE_EVIDENCE_PRESENT',
        policy: { approvalReductionRecommended: false },
      },
      operatingCosts: {
        totals: { knownOperatingCostUsd: '12.00000000' },
        policy: { anomalyThreshold: 'UNRESOLVED' },
      },
      recentConversation: [],
      authority: {
        transport: 'PLATFORM_ADMIN_SESSION_ONLY',
        customerCredentialCompatible: false,
        canExecute: false,
        canApprove: false,
        canAcknowledge: false,
        canMutatePolicy: false,
      },
    })
  })
})
