import { db, listFounderOperatingExchanges } from '@pathfinder/db'
import { readAgentEvidenceRows } from './attention-agent-evidence-query'
import {
  ACTIVE_SUPPORT_REQUEST_STATUSES,
  after,
  type AttentionConsoleInput,
} from './attention-pagination'
import { listAttentionWorkers } from './attention-worker-health'
import { readFounderUnitEconomics } from './unit-economics'
import { customerAccessApprovalSelect } from './customer-access-approval-select'
import { attentionQuestionSelect } from './attention-priority-questions'
import { readFailedAttentionJobs } from './attention-console-failed-jobs'
import { readFounderBriefingReview } from './attention-review-actions'
import { readAttentionEvaluations } from './attention-console-evaluations'

export async function readAttentionConsoleRows(
  operatorUserId: string,
  query: AttentionConsoleInput,
  now: Date,
  take: number,
) {
  const [
    jobs,
    evaluations,
    approvals,
    support,
    agents,
    questions,
    priorityQuestions,
    workingAgents,
    blockedAgents,
    completedAgents,
    outcomes,
    agentEvidenceRows,
    events,
    criticalEvents,
    errorEvents,
    platformEvents,
    criticalPlatformEvents,
    errorPlatformEvents,
    workers,
    reviewState,
    unitEconomics,
    founderConversation,
  ] = await Promise.all([
    readFailedAttentionJobs(query.jobsCursor, take),
    readAttentionEvaluations(query.evaluationsCursor, now, take),
    db.approvalRequest.findMany({
      where: { decision: { is: null }, ...after(query.approvalsCursor) },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        proposedAction: true,
        riskCategory: true,
        expiresAt: true,
        createdAt: true,
        agentIdentity: { select: { name: true } },
        customerAccessRequest: {
          select: customerAccessApprovalSelect,
        },
        founderDirectiveTask: {
          select: {
            id: true,
            status: true,
            proposedPrompt: true,
            rationale: true,
            constraints: true,
            founderOperatingExchange: { select: { prompt: true } },
          },
        },
      },
    }),
    db.supportRequest.findMany({
      where: {
        status: { in: [...ACTIVE_SUPPORT_REQUEST_STATUSES] },
        ...after(query.supportCursor),
      },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        category: true,
        status: true,
        subject: true,
        version: true,
        updatedAt: true,
        createdAt: true,
        onboardingQuestionLink: {
          select: { id: true, agentQuestionId: true },
        },
      },
    }),
    db.agentRun.findMany({
      where: after(query.agentsCursor),
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        agentIdentityId: true,
        tenantId: true,
        venueId: true,
        runType: true,
        requestedOperation: true,
        status: true,
        startedAt: true,
        completedAt: true,
        createdAt: true,
        agentIdentity: { select: { id: true, name: true } },
      },
    }),
    db.agentQuestion.findMany({
      where: { status: 'PENDING', ...after(query.questionsCursor) },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: attentionQuestionSelect,
    }),
    db.agentQuestion.findMany({
      where: {
        status: 'PENDING',
        OR: [{ blocking: true }, { urgency: 'URGENT' }],
      },
      orderBy: [{ urgency: 'desc' }, { blocking: 'desc' }, { createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: attentionQuestionSelect,
    }),
    db.agentRun.findMany({
      where: {
        status: { in: ['QUEUED', 'RUNNING'] },
        ...after(query.workingAgentsCursor),
      },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        runType: true,
        requestedOperation: true,
        status: true,
        startedAt: true,
        createdAt: true,
        agentIdentity: { select: { name: true } },
      },
    }),
    db.agentRun.findMany({
      where: {
        status: { in: ['AWAITING_INPUT', 'AWAITING_APPROVAL', 'FAILED'] },
        ...after(query.blockedAgentsCursor),
      },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        runType: true,
        requestedOperation: true,
        status: true,
        errorCode: true,
        createdAt: true,
        agentIdentity: { select: { name: true } },
      },
    }),
    db.agentRun.findMany({
      where: { status: 'COMPLETED', ...after(query.completedAgentsCursor) },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        agentIdentityId: true,
        tenantId: true,
        venueId: true,
        runType: true,
        requestedOperation: true,
        status: true,
        completedAt: true,
        createdAt: true,
        agentIdentity: { select: { id: true, name: true } },
        _count: { select: { outcomeObservations: true } },
      },
    }),
    db.agentOutcomeObservation.findMany({
      where: after(query.outcomesCursor),
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        agentRunId: true,
        agentIdentityId: true,
        signalKind: true,
        verdict: true,
        summary: true,
        relatedAgentActionId: true,
        policyCode: true,
        severity: true,
        predictionRef: true,
        predictedConfidenceBps: true,
        actualCorrect: true,
        taskClass: true,
        modelProvider: true,
        modelName: true,
        createdAt: true,
        agentIdentity: { select: { id: true, name: true } },
      },
    }),
    readAgentEvidenceRows(db, take),
    db.operationalEvent.findMany({
      where: {
        state: { in: ['OPEN', 'ACKNOWLEDGED'] },
        ...after(query.eventsCursor),
      },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        eventType: true,
        sourceSubsystem: true,
        severity: true,
        title: true,
        summary: true,
        actionRequired: true,
        linkedObjectType: true,
        linkedObjectId: true,
        recommendedAction: true,
        state: true,
        occurrenceCount: true,
        lastOccurredAt: true,
        createdAt: true,
      },
    }),
    db.operationalEvent.findMany({
      where: {
        state: { in: ['OPEN', 'ACKNOWLEDGED'] },
        actionRequired: true,
        severity: 'CRITICAL',
      },
      orderBy: [{ lastOccurredAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        eventType: true,
        sourceSubsystem: true,
        severity: true,
        title: true,
        summary: true,
        actionRequired: true,
        linkedObjectType: true,
        linkedObjectId: true,
        recommendedAction: true,
        state: true,
        occurrenceCount: true,
        lastOccurredAt: true,
        createdAt: true,
      },
    }),
    db.operationalEvent.findMany({
      where: {
        state: { in: ['OPEN', 'ACKNOWLEDGED'] },
        actionRequired: true,
        severity: 'ERROR',
      },
      orderBy: [{ lastOccurredAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        tenantId: true,
        venueId: true,
        eventType: true,
        sourceSubsystem: true,
        severity: true,
        title: true,
        summary: true,
        actionRequired: true,
        linkedObjectType: true,
        linkedObjectId: true,
        recommendedAction: true,
        state: true,
        occurrenceCount: true,
        lastOccurredAt: true,
        createdAt: true,
      },
    }),
    db.platformOperationalEvent.findMany({
      where: {
        state: { in: ['OPEN', 'ACKNOWLEDGED'] },
        ...after(query.platformEventsCursor),
      },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        eventType: true,
        sourceSubsystem: true,
        severity: true,
        title: true,
        summary: true,
        actionRequired: true,
        linkedObjectType: true,
        linkedObjectId: true,
        recommendedAction: true,
        state: true,
        occurrenceCount: true,
        lastOccurredAt: true,
        createdAt: true,
      },
    }),
    db.platformOperationalEvent.findMany({
      where: {
        state: { in: ['OPEN', 'ACKNOWLEDGED'] },
        actionRequired: true,
        severity: 'CRITICAL',
      },
      orderBy: [{ lastOccurredAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        eventType: true,
        sourceSubsystem: true,
        severity: true,
        title: true,
        summary: true,
        actionRequired: true,
        linkedObjectType: true,
        linkedObjectId: true,
        recommendedAction: true,
        state: true,
        occurrenceCount: true,
        lastOccurredAt: true,
        createdAt: true,
      },
    }),
    db.platformOperationalEvent.findMany({
      where: {
        state: { in: ['OPEN', 'ACKNOWLEDGED'] },
        actionRequired: true,
        severity: 'ERROR',
      },
      orderBy: [{ lastOccurredAt: 'desc' }, { id: 'desc' }],
      take,
      select: {
        id: true,
        eventType: true,
        sourceSubsystem: true,
        severity: true,
        title: true,
        summary: true,
        actionRequired: true,
        linkedObjectType: true,
        linkedObjectId: true,
        recommendedAction: true,
        state: true,
        occurrenceCount: true,
        lastOccurredAt: true,
        createdAt: true,
      },
    }),
    listAttentionWorkers(now),
    readFounderBriefingReview(operatorUserId),
    readFounderUnitEconomics(now),
    listFounderOperatingExchanges(20),
  ])

  return {
    jobs,
    evaluations,
    approvals,
    support,
    agents,
    questions,
    priorityQuestions,
    workingAgents,
    blockedAgents,
    completedAgents,
    outcomes,
    agentEvidenceRows,
    events,
    criticalEvents,
    errorEvents,
    platformEvents,
    criticalPlatformEvents,
    errorPlatformEvents,
    workers,
    reviewState,
    unitEconomics,
    founderConversation,
  }
}
