export const TENANTED_TABLES = [
  'TenantMembership',
  'TenantFeatureFlag',
  'Venue',
  'Place',
  'VenueKnowledgeEntry',
  'ContentVersion',
  'EvalCase',
  'EvalRun',
  'EvalRunCostReservation',
  'EvalResult',
  'EvalReview',
  'VenueContentImportReceipt',
  'VenuePackage',
  'VenuePackageManifestArtifact',
  'VenuePackageDuplicateAnalysis',
  'VisitorSession',
  'GuestChatTurn',
  'GuestChatProviderOperation',
  'AiUsageEvent',
  'AiUsageDailyRollup',
  'AiCostBudget',
  'AiCostReservation',
  'Message',
  'OperationalUpdate',
  'AnalyticsEvent',
  'DailyRollup',
  'WeeklyDigest',
  'QuestionCluster',
  'EngagementQuestion',
  'EngagementQuestionResponse',
  'AdminChatlogNote',
  'WeeklyReport',
  'VenueReportConfiguration',
  'AnswerAnalysisSnapshot',
  'GenerationRequestDispatch',
  'VenueWeeklyTheme',
  'MediaIngestionProject',
  'MediaIngestionAsset',
  'EmbeddingWorkClaim',
  'EmbeddingDispatch',
  'AgentIdentity',
  'AgentRun',
  'AgentAction',
  'AgentTimelineEvent',
  'ApprovalRequest',
  'ApprovalDecision',
  'SupportRequest',
  'SupportRequestParticipant',
  'SupportMessage',
  'SupportMessageAttachment',
  'SupportRequestAuditEvent',
  'SupportPackageHandoff',
  'SupportPreviewFeedback',
  'ExternalAccessCredential',
  'ExternalCredentialRotation',
  'ExternalCredentialRevocation',
  'OffboardingPlan',
  'OffboardingVenueTarget',
  'OffboardingRevocationEvidence',
  'OffboardingExportArtifact',
  'ContentModuleIdentity',
  'ContentModuleRevision',
  'ServiceContent',
  'PolicyContent',
  'EventContent',
  'OperationalFactContent',
  'RelationshipContent',
  'ContentModuleEvidence',
  'ContentModulePublication',
  'IntakeRun',
  'IntakeEvidenceRecord',
  'IntakeRunEvent',
  'IntakePackageHandoff',
  'IntakeUpload',
  'AiScopedWorkloadConfigurationOverride',
  'AiScopedWorkloadConfigurationHistory',
] as const

export const PLATFORM_TABLES = [
  'User',
  'Tenant',
  'PlatformConfig',
  'ClerkWebhookReceipt',
  'AiWorkloadConfigurationOverride',
  'AiWorkloadConfigurationHistory',
  'ClientCreateIntent',
  'ClientCreateIntentEvent',
] as const

// Models in this list deliberately support both tenant-attributed and
// platform-wide rows. They must remain explicit because neither silently
// treating them as platform tables nor forcing tenant scope is correct.
export const SHARED_SCOPE_TABLES = ['AuditLog', 'JobRecord'] as const

export type TenantedTable = (typeof TENANTED_TABLES)[number]
export type PlatformTable = (typeof PLATFORM_TABLES)[number]
export type SharedScopeTable = (typeof SHARED_SCOPE_TABLES)[number]
