export const TENANTED_TABLES = [
  'TenantMembership',
  'TenantFeatureFlag',
  'ProductEntitlementOverride',
  'BillingAccount',
  'CommercialAgreement',
  'CommercialAgreementVenue',
  'BillingCheckoutAttempt',
  'BillingInvoiceProjection',
  'BillingEventApplication',
  'BillingReconciliationRun',
  'BillingAccessOverride',
  'BillingCustomerRequest',
  'BillingAgentCommand',
  'Venue',
  'VenueBotConfiguration',
  'PersonalityProfile',
  'CustomCharacter',
  'ClientAssistantPreference',
  'ClientAssistantThread',
  'ClientAssistantTurn',
  'ClientAssistantSupportHandoff',
  'Place',
  'VenueKnowledgeEntry',
  'ContentVersion',
  'EvalCase',
  'EvalRun',
  'EvalRunCostReservation',
  'EvalResult',
  'EvalReview',
  'OnboardingMilestoneEvent',
  'VenueContentImportReceipt',
  'VenuePackage',
  'VenuePackageManifestArtifact',
  'NativeVenueDeploymentArtifact',
  'NativeVenueDeploymentRelease',
  'NativeVenueDeploymentEffect',
  'NativeVenueDeploymentHead',
  'NativeVenueDeploymentCommand',
  'NativeVenueDeploymentPublicationLineage',
  'NativeVenueDeploymentEvaluationEvidence',
  'VenuePackageDuplicateAnalysis',
  'VisitorSession',
  'VoiceSession',
  'VoiceTranscriptSegment',
  'GuestChatTurn',
  'GuestChatProviderOperation',
  'AiUsageEvent',
  'ConversationInsight',
  'OperationalEvent',
  'OperationalEventDelivery',
  'OperationalEventDeliveryAttempt',
  'KnowledgeChangeProposal',
  'VenueFloor',
  'VenueLocation',
  'VenueLocationConnection',
  'AiUsageDailyRollup',
  'AiCostBudget',
  'AiCostReservation',
  'Message',
  'MessageFeedback',
  'OperationalUpdate',
  'AnalyticsEvent',
  'DailyRollup',
  'WeeklyDigest',
  'QuestionCluster',
  'EngagementQuestion',
  'EngagementQuestionResponse',
  'AdminChatlogNote',
  'WeeklyReport',
  'VenueReportConfiguration',
  'AnswerAnalysisSnapshot',
  'GenerationRequestDispatch',
  'VenueWeeklyTheme',
  'MediaIngestionProject',
  'MediaIngestionAsset',
  'EmbeddingWorkClaim',
  'EmbeddingDispatch',
  'AgentIdentity',
  'AgentBridgeSession',
  'AgentWorker',
  'AgentRun',
  'AgentAction',
  'AgentTimelineEvent',
  'AgentMessage',
  'AgentOutcomeObservation',
  'AgentQuestion',
  'OnboardingQuestionLink',
  'ApprovalRequest',
  'ApprovalDecision',
  'ApprovalGrant',
  'ApprovalGrantConsumption',
  'SupportRequest',
  'SupportRequestParticipant',
  'SupportMessage',
  'SupportMessageAttachment',
  'SupportRequestAuditEvent',
  'SupportPackageHandoff',
  'SupportPreviewFeedback',
  'SupportAgentRunLineage',
  'ExternalAccessCredential',
  'ExternalCredentialOperationReceipt',
  'ExternalCredentialRotation',
  'ExternalCredentialRevocation',
  'ExternalCredentialActivation',
  'OffboardingPlan',
  'OffboardingVenueTarget',
  'OffboardingRevocationEvidence',
  'OffboardingExportArtifact',
  'OffboardingExportOperation',
  'ContentModuleIdentity',
  'ContentModuleRevision',
  'ItemContent',
  'ServiceContent',
  'PolicyContent',
  'EventContent',
  'OperationalFactContent',
  'RelationshipContent',
  'ContentModuleEvidence',
  'ContentModulePublication',
  'IntakeRun',
  'IntakeEvidenceRecord',
  'IntakeRunEvent',
  'IntakePackageHandoff',
  'IntakeUpload',
  'IntakeUploadVerificationReceipt',
  'AiScopedWorkloadConfigurationOverride',
  'AiScopedWorkloadConfigurationHistory',
  // Durable bridge from a platform prospect to one exact customer tenant.
  'ProspectConversion',
  // Customer relationship bridges are exact-tenant scoped even though the
  // prospect records on their other side are platform-owned.
  'ProspectCustomerRelationship',
  'ProspectLocationConversion',
] as const

export const PLATFORM_TABLES = [
  'User',
  'Tenant',
  'PlatformConfig',
  'ClerkWebhookReceipt',
  'AiWorkloadConfigurationOverride',
  'AiWorkloadConfigurationHistory',
  'ClientCreateIntent',
  'ClientCreateIntentEvent',
  'ProductPlanCapability',
  // Provider receipt exists before tenant ownership can be established so
  // unknown Stripe objects can be quarantined instead of discarded.
  'StripeWebhookReceipt',
  'ProspectTerritory',
  'ProspectTag',
  'ProspectOrganizationTag',
  'CorrespondenceProviderAccount',
  // Google source cursors and raw transcript artifacts are provider-account-owned intake state.
  // Customer-scoped durable knowledge is projected separately through shared-scope meetings and
  // provenance-bearing Company Brain records.
  'GoogleCalendarSyncState',
  'CompanyMeetingTranscriptArtifact',
  'ProspectDeliveryControl',
  'ProspectOrganization',
  // Prospect research is platform acquisition work. Jobs and immutable attempts are scoped through
  // their exact platform-owned organization relation and never inherit customer tenant authority.
  'ProspectResearchJob',
  'ProspectResearchAttempt',
  'ProspectVenue',
  'ProspectContact',
  'ProspectContactSuppressionEvent',
  'ProspectOpportunity',
  'ProspectStageHistory',
  'ProspectActivity',
  'ProspectSourceEvidence',
  'ProspectDuplicateCandidate',
  'ProspectImport',
  'ProspectImportSheet',
  'ProspectImportRow',
  'ProspectImportReportEntry',
  // Immutable staging-package source lineage belongs to the platform import that admitted it.
  'ProspectImportSourceRecord',
  'ProspectSavedView',
  'ProspectOutreachCampaign',
  'ProspectCampaignMember',
  'ProspectOutreachDraft',
  'ProspectSendBatch',
  'ProspectSendItem',
  'ProspectSendOutbox',
  'ProspectEmailThread',
  'ProspectEmailThreadProvider',
  'ProspectEmailMessage',
  'ProspectEmailEvent',
  'ProspectFollowup',
  'ProspectEmailWebhookReceipt',
  'PlatformOperationalEvent',
  'EncryptedIntegrationCredential',
  'GmailOAuthAttempt',
  'ProspectInboundQuarantine',
] as const

// Models in this list deliberately support both tenant-attributed and
// platform-wide rows. They must remain explicit because neither silently
// treating them as platform tables nor forcing tenant scope is correct.
export const SHARED_SCOPE_TABLES = [
  'AuditLog',
  'JobRecord',
  'CompanyKnowledgeItem',
  'CompanyKnowledgeRevision',
  'CompanyKnowledgeSource',
  'CompanyKnowledgeEntityLink',
  'CompanyKnowledgeRelation',
  'CompanyDecision',
  'CompanyPriority',
  'AccountRelationshipNote',
  'AccountMilestone',
  'AccountOpenLoop',
  'AccountCommitment',
  'AccountSummary',
  'CompanyMeeting',
  'CompanyMeetingParticipant',
  'CompanyMeetingExtraction',
] as const

export type TenantedTable = (typeof TENANTED_TABLES)[number]
export type PlatformTable = (typeof PLATFORM_TABLES)[number]
export type SharedScopeTable = (typeof SHARED_SCOPE_TABLES)[number]
