import type { AdminContextRoute } from './CopyForCodex'

const route = (
  routeTemplate: string,
  pageName: string,
  procedures: readonly string[] = [],
  registryFiles: readonly string[] = [],
  mcp: readonly string[] = ['pathfinder.read'],
): AdminContextRoute => ({
  routeTemplate,
  match: new RegExp(
    `^${routeTemplate.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&').replace(/\\\[[^/]+\\\]/gu, '[^/]+')}$`,
    'u',
  ),
  pageName,
  mcp,
  procedures,
  registryFiles,
})

/** One reviewed mapping per current admin page route. */
export const ADMIN_AGENT_SURFACE_MAP: readonly AdminContextRoute[] = [
  route(
    '/admin',
    'Needs you',
    [
      'admin.overview',
      'admin.getGlobalAiControl',
      'admin.getAiProviderHealthControl',
      'admin.attentionConsole',
    ],
    ['overview.ts', 'incident-control.ts', 'attention-console-router.ts'],
  ),
  route(
    '/admin/ai',
    'AI systems',
    ['admin.getAdminAiSystems', 'admin.listPlatformWorkerPolicyCredentials'],
    ['ai-workload-configuration.ts', 'platform-worker-policy-credentials.ts'],
  ),
  route('/admin/billing', 'Billing', ['admin.listBillingPortfolio'], ['billing-portfolio.ts']),
  route(
    '/admin/character-lab',
    'Character lab',
    ['admin.prepareCharacterFactoryJob'],
    ['character-factory.ts'],
  ),
  route(
    '/admin/clients/[tenantId]',
    'Client overview',
    ['admin.getClient', 'admin.getAiCostBudget', 'admin.getTochiRollout'],
    ['client-reads.ts', 'cost-budget.ts', 'tochi-rollout.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/analytics',
    'Client analytics',
    ['admin.getClientAnalytics'],
    ['client-analytics.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/billing',
    'Client billing',
    ['admin.getClientBilling', 'admin.getClient', 'admin.getBillingRollout'],
    ['billing.ts', 'client-reads.ts', 'billing-rollout.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/credentials',
    'Client credentials',
    ['admin.getClient', 'admin.listExternalCredentials', 'admin.getExternalCredential'],
    ['client-reads.ts', 'external-credentials.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/offboarding',
    'Client offboarding',
    [
      'admin.getClient',
      'admin.listOffboardingPlans',
      'admin.getCustomerStatePreservation',
      'admin.getOffboardingPlan',
    ],
    ['client-reads.ts', 'offboarding-plans.ts', 'offboarding-export-preview.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]',
    'Venue overview',
    ['admin.getClientVenue', 'admin.getVenueAvailability', 'admin.getSecondLayerEntitlement'],
    ['client-reads.ts', 'venue-availability.ts', 'second-layer.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/agents',
    'Venue agents',
    [
      'admin.listAgentIdentities',
      'admin.listAgentRuns',
      'admin.listApprovalRequests',
      'admin.listAgentQuestions',
    ],
    [
      'agent-identity-reads.ts',
      'agent-operations.ts',
      'agent-approval-request-reads.ts',
      'agent-question-history.ts',
    ],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/agents/integrations',
    'Agent integrations',
    ['admin.listAgentBridgeSessions', 'admin.listAgentIdentities'],
    ['agent-bridge-operations.ts', 'agent-identity-reads.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/agents/routines',
    'Agent routines',
    ['admin.listAgentRoutines', 'admin.listAgentIdentities'],
    ['agent-routines.ts', 'agent-identity-reads.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/agents/runs/[runId]',
    'Agent run details',
    [
      'admin.getAgentRun',
      'admin.listAgentRunActions',
      'admin.listAgentRunTimeline',
      'admin.listAgentRunTrace',
    ],
    ['agent-operations.ts', 'agent-run-trace.ts'],
  ),
  route('/admin/clients/[tenantId]/venues/[venueId]/agents/settings', 'Agent settings'),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/ai-configuration',
    'AI configuration',
    ['admin.getVenueAiWorkloadConfiguration'],
    ['ai-workload-configuration.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/analysis',
    'Answer analyses',
    ['admin.listAnswerAnalyses'],
    ['answer-analysis.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/analysis/[snapshotId]',
    'Answer analysis detail',
    ['admin.getAnswerAnalysis'],
    ['answer-analysis.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/chatlogs',
    'Conversations',
    ['admin.listVenueSessions'],
    ['chatlogs.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/chatlogs/[sessionId]',
    'Conversation details',
    ['admin.getSessionChatlog'],
    ['chatlogs.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/compatibility-content',
    'Older content format',
    ['admin.listLegacyContent'],
    ['legacy-content.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/content',
    'Venue content',
    ['admin.listUniversalContent'],
    ['universal-content.ts'],
  ),
  route('/admin/clients/[tenantId]/venues/[venueId]/deployment-manifest', 'Deployment manifest'),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/evaluations',
    'Evaluations',
    [
      'admin.listEvaluationRuns',
      'admin.listEvaluationCases',
      'admin.listOnboardingEvaluationPackages',
      'admin.getOnboardingMilestoneRollup',
      'admin.listEvaluationSourceInsights',
      'admin.listRejectedConversationCandidates',
      'admin.listGuestAnswerAttributionEvaluationRequests',
    ],
    [
      'evaluation-operations.ts',
      'evaluation-onboarding-reads.ts',
      'evaluation-conversation-cases.ts',
      'guest-answer-attributions.ts',
    ],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/feature-access',
    'Feature access',
    ['admin.getClientVenue', 'admin.listProductEntitlements'],
    ['client-reads.ts', 'product-entitlements.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/freshness',
    'Content freshness',
    ['admin.listFreshnessAudit'],
    ['freshness-audit.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/guest-design',
    'Guest design',
    ['admin.getGuestDesign', 'admin.listGuestBrandingAssets'],
    ['guest-design.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/intake',
    'Guided intake',
    [
      'admin.listIntakeProposals',
      'admin.listOnboardingBootstrapDetails',
      'admin.listIntakeUploads',
    ],
    ['intake-operations.ts', 'intake-upload-review.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/knowledge-proposals',
    'Knowledge proposals',
    [
      'admin.listKnowledgeProposals',
      'admin.getConversationLearningPolicy',
      'admin.listConversationLearningCandidates',
    ],
    ['knowledge-proposal-reads.ts', 'conversation-learning.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/locations',
    'Venue locations',
    ['admin.getVenueLocationAuthoring'],
    ['location-authoring.ts'],
  ),
  route('/admin/clients/[tenantId]/venues/[venueId]/media', 'Venue media'),
  route('/admin/clients/[tenantId]/venues/[venueId]/media/[projectId]', 'Venue media project'),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/native-releases',
    'Full content releases',
    [
      'admin.listNativeVenueDeployments',
      'admin.getNativeContentConvergence',
      'admin.getNativeGuestReadActivationPreflight',
      'admin.getNativeVenueDeployment',
    ],
    ['native-venue-deployments.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/packages',
    'Venue packages',
    ['admin.listVenuePackagesForReview', 'admin.getVenuePackageForReview'],
    ['venue-package-operations.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/qr-kit',
    'QR kit',
    ['admin.getClientVenue', 'admin.getVenueLaunchAsset'],
    ['client-reads.ts', 'venue-launch-assets.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/reports',
    'Venue reports',
    ['admin.listWeeklyReports', 'admin.getVenueReportConfiguration'],
    ['weekly-reports.ts', 'report-configuration.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/reports/[reportId]',
    'Venue report details',
    [
      'admin.getWeeklyReport',
      'admin.getWeeklyReportLifecycle',
      'admin.getVenueReportConfiguration',
    ],
    ['weekly-reports.ts', 'weekly-report-lifecycle.ts', 'report-configuration.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/support-operations',
    'Venue support',
    [
      'admin.listSupportRequests',
      'admin.listEligibleSupportAttachments',
      'admin.getSupportRequest',
      'admin.listSupportMessages',
      'admin.listSupportAuditEvents',
    ],
    ['support-operations.ts', 'support-attachments.ts'],
  ),
  route(
    '/admin/clients/[tenantId]/venues/[venueId]/visitor-access',
    'Visitor access',
    ['admin.venueDistribution.get'],
    ['venue-distribution.ts'],
  ),
  route(
    '/admin/company-brain',
    'Company Brain',
    ['admin.listCompanyBrain'],
    ['company-brain.ts'],
    ['torchiko.account.get_context', 'torchiko.knowledge.search'],
  ),
  route(
    '/admin/directory',
    'Client directory',
    ['admin.searchClients'],
    ['client-directory-search.ts'],
  ),
  route('/admin/help', 'Operator guide'),
  route('/admin/new', 'New client', ['admin.createClient'], ['client-management.ts']),
  route(
    '/admin/operations',
    'System',
    [
      'admin.attentionConsole',
      'admin.operationsReadiness',
      'admin.releaseEvidence',
      'admin.getGlobalAiControl',
      'admin.getAiProviderHealthControl',
      'admin.listCharacterCandidateReviews',
    ],
    [
      'attention-console-router.ts',
      'operations-readiness.ts',
      'release-evidence.ts',
      'incident-control.ts',
      'character-candidate-reviews.ts',
    ],
  ),
  route(
    '/admin/prospects',
    'Prospects',
    ['admin.listProspectTerritories', 'admin.listProspectSavedViews', 'admin.listProspects'],
    ['prospect-crm-territories.ts', 'prospect-crm-saved-views.ts', 'prospect-crm-directory.ts'],
  ),
  route(
    '/admin/prospects/[prospectId]',
    'Prospect details',
    ['admin.getProspect', 'admin.getProspectIntelligence'],
    ['prospect-crm-core.ts', 'prospect-crm-intelligence.ts'],
  ),
  route('/admin/prospects/duplicates', 'Prospect duplicates'),
  route('/admin/prospects/imports', 'Prospect imports'),
  route('/admin/prospects/inbound', 'Inbound prospects'),
  route('/admin/prospects/new', 'New prospect'),
  route('/admin/prospects/outreach', 'Prospect outreach'),
  route('/admin/prospects/outreach/[campaignId]', 'Outreach campaign details'),
  route(
    '/admin/prospects/pipeline',
    'Prospect pipeline',
    ['admin.getProspectPipeline'],
    ['prospect-crm-core.ts'],
  ),
  route('/admin/prospects/review-proposals', 'Prospect proposals'),
]
