/* @vitest-environment jsdom */
import React from 'react'
import { cleanup, render, screen } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import type { SalesWorkflowView } from '@pathfinder/api/prospect-sales-contract'
import { ProspectOperationalHandoff } from './ProspectOperationalHandoff'
;(globalThis as typeof globalThis & { React: typeof React }).React = React
afterEach(cleanup)

it('shows the AI/model role on a retained operational candidate', () => {
  const view = {
    venueId: 'SYN-venue',
    snapshotHash: 'a'.repeat(64),
    routing: null,
    operational: {
      rehearsal: true,
      liveSendAvailable: false,
      accounts: [],
      correspondence: [],
      candidate: {
        id: 'SYN-candidate',
        campaignId: 'SYN-campaign',
        status: 'NEEDS_REVIEW',
        contentHash: 'b'.repeat(64),
        recipient: 'fixture@example.invalid',
        subject: 'Diagnostic',
        body: 'No send requested.',
        generatedBy: 'Tom',
        generatedByKind: 'AGENT',
        approvedBy: null,
        sourceDraftId: 'SYN-draft',
        meaningReviewId: 'SYN-meaning',
        providerAccountId: 'SYN-account',
        staleReason: null,
        escalationFlags: [],
        synthetic: true,
        batch: null,
      },
    },
  } as unknown as SalesWorkflowView
  render(<ProspectOperationalHandoff view={view} enabled={false} onAction={vi.fn()} />)
  expect(screen.getByText(/Generated by AI agent\/model:/)).toBeTruthy()
  expect(screen.getByText('Tom')).toBeTruthy()
})
