import {
  bucket,
  defineRailway,
  github,
  image,
  preserve,
  project,
  redis,
  service,
  volume,
} from 'railway/iac'

export default defineRailway(() => {
  const pathfinder = github('tomschoenekase-dotcom/pathfinder', {
    branch: 'codex/pathfinder-v2-staging',
    checkSuites: true,
  })

  const Redis5Vrb = redis('Redis-5Vrb', { region: 'europe-west4-drams3a' })
  Redis5Vrb.deploy = {
    startCommand:
      '/bin/sh -c "rm -rf $RAILWAY_VOLUME_MOUNT_PATH/lost+found/ && exec docker-entrypoint.sh redis-server --requirepass $REDIS_PASSWORD --save 60 1 --dir $RAILWAY_VOLUME_MOUNT_PATH"',
  }
  const redisVolumePu8X = volume('redis-volume-Pu8X', {
    alerts: { usage: { '100': {}, '80': {}, '95': {} } },
    allowOnlineResize: true,
    region: 'europe-west4-drams3a',
    sizeMB: 5000,
  })
  const pgvectorVolume = volume('pgvector-volume', {
    alerts: { usage: { '100': {}, '80': {}, '95': {} } },
    allowOnlineResize: true,
    region: 'europe-west4-drams3a',
    sizeMB: 5000,
  })
  const reservedTote = bucket('reserved-tote', { region: 'ams' })
  const clamav = service('clamav', {
    source: image('clamav/clamav:stable'),
    replicas: { 'europe-west4-drams3a': 1 },
  })
  const pgvector = service('pgvector', {
    source: image('pgvector/pgvector:0.8.0-pg17'),
    replicas: { 'europe-west4-drams3a': 1 },
    volumeMounts: { '/var/lib/postgresql/data': pgvectorVolume },
    env: {
      DATABASE_URL: preserve(),
      DIRECT_DATABASE_URL: preserve(),
      PGDATA: preserve(),
      POSTGRES_DB: preserve(),
      POSTGRES_INITDB_ARGS: preserve(),
      POSTGRES_PASSWORD: preserve(),
      POSTGRES_USER: preserve(),
    },
  })
  const stagingWorkers = service('staging-workers', {
    source: pathfinder,
    build: {
      builder: 'DOCKERFILE',
      dockerfilePath: 'Dockerfile.workers',
    },
    deploy: {
      restartPolicyType: 'ON_FAILURE',
      restartPolicyMaxRetries: 5,
    },
    replicas: { 'europe-west4-drams3a': 1 },
    env: {
      BILLING_ENTITLEMENT_ENFORCEMENT_ENABLED: preserve(),
      BILLING_GRACE_PERIOD_DAYS: preserve(),
      CLERK_PUBLISHABLE_KEY: preserve(),
      CLERK_SECRET_KEY: preserve(),
      CRM_BACKGROUND_WORKERS_ENABLED: preserve(),
      DASHBOARD_URL: preserve(),
      DATABASE_RESOURCE_ID: preserve(),
      DATABASE_URL: preserve(),
      DIRECT_DATABASE_URL: preserve(),
      EMBEDDING_DISPATCH_ENABLED: preserve(),
      EVALUATION_RUNNER_ENABLED: preserve(),
      FOUNDER_ABSENCE_OBSERVER_ENABLED: preserve(),
      GENERATION_DISPATCH_ENABLED: preserve(),
      GENERATION_RECOVERY_ENABLED: preserve(),
      INTAKE_UPLOAD_VERIFICATION_WORKERS_ENABLED: preserve(),
      OPENAI_API_KEY: preserve(),
      OUTBOUND_PROVIDER_WORKERS_ENABLED: preserve(),
      PATHFINDER_ALLOW_STAGING_MIGRATIONS: preserve(),
      PATHFINDER_RELEASE_SHA: preserve(),
      PATHFINDER_STAGING_LOCAL_UPLOAD_APPROVAL: preserve(),
      RAILWAY_ENVIRONMENT: preserve(),
      RAILWAY_RELEASE_SHA: preserve(),
      REDIS_RESOURCE_ID: preserve(),
      REDIS_URL: preserve(),
      STORAGE_ACCESS_KEY_ID: preserve(),
      STORAGE_BUCKET: preserve(),
      STORAGE_ENDPOINT: preserve(),
      STORAGE_REGION: preserve(),
      STORAGE_RESOURCE_ID: preserve(),
      STORAGE_SECRET_ACCESS_KEY: preserve(),
      STRIPE_ACCOUNT_NAMESPACE: preserve(),
      STRIPE_BILLING_UI_ENABLED: preserve(),
      STRIPE_CANCELLATION_ENABLED: preserve(),
      STRIPE_CATALOG_JSON: preserve(),
      STRIPE_CHECKOUT_ENABLED: preserve(),
      STRIPE_CUSTOMER_PORTAL_ENABLED: preserve(),
      STRIPE_LIVE_MODE_ALLOWED: preserve(),
      STRIPE_MODE: preserve(),
      STRIPE_RECONCILIATION_ENABLED: preserve(),
      STRIPE_SECRET_KEY: preserve(),
      STRIPE_WEBHOOK_PROCESSING_ENABLED: preserve(),
      VENUE_MEDIA_DERIVATIVE_WORKERS_ENABLED: preserve(),
      VOICE_MODE_ENABLED: preserve(),
      WORKER_SCHEDULERS_ENABLED: preserve(),
    },
  })
  const stagingWeb = service('staging-web', {
    source: pathfinder,
    build: {
      builder: 'DOCKERFILE',
      dockerfilePath: 'Dockerfile.web.staging',
    },
    deploy: {
      preDeployCommand: ['node /migration/scripts/run-staging-migration-predeploy.mjs'],
      healthcheckPath: '/api/health',
      restartPolicyType: 'ON_FAILURE',
      restartPolicyMaxRetries: 3,
    },
    replicas: { 'europe-west4-drams3a': 1 },
    env: {
      CLERK_PUBLISHABLE_KEY: preserve(),
      CLERK_SECRET_KEY: preserve(),
      CRM_PROSPECT_OUTREACH_ENABLED: preserve(),
      DATABASE_RESOURCE_ID: preserve(),
      DATABASE_URL: preserve(),
      DIRECT_DATABASE_URL: preserve(),
      EMBEDDING_DISPATCH_ENABLED: preserve(),
      EMBED_PREVIEW_ENABLED: preserve(),
      EVALUATION_RUNNER_ENABLED: preserve(),
      FOUNDER_ABSENCE_OBSERVER_ENABLED: preserve(),
      GENERALIZED_CONTENT_CAPABILITIES_ENABLED: preserve(),
      GENERATION_DISPATCH_ENABLED: preserve(),
      GENERATION_RECOVERY_ENABLED: preserve(),
      INTAKE_CLAMAV_HOST: preserve(),
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: preserve(),
      NEXT_PUBLIC_PWA_ENABLED: preserve(),
      NEXT_PUBLIC_SENTRY_ENABLED: preserve(),
      NEXT_PUBLIC_SENTRY_ENVIRONMENT: preserve(),
      NEXT_PUBLIC_WEB_URL: preserve(),
      OPENAI_API_KEY: preserve(),
      OUTBOUND_PROVIDER_WORKERS_ENABLED: preserve(),
      PATHFINDER_ALLOW_STAGING_MIGRATIONS: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATABASE_HOST: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATABASE_NAME: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATABASE_RESOURCE: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATA_POLICY: preserve(),
      PATHFINDER_CONFIRM_STAGING_DIRECT_DATABASE_HOST: preserve(),
      PATHFINDER_RELEASE_SHA: preserve(),
      PATHFINDER_STAGING_DATABASE_RESOURCE: preserve(),
      PATHFINDER_STAGING_LOCAL_UPLOAD_APPROVAL: preserve(),
      PATHFINDER_STAGING_MIGRATION_APPROVAL: preserve(),
      PATHFINDER_STAGING_SPEND_CEILING_USD: preserve(),
      RAILWAY_ENVIRONMENT: preserve(),
      RAILWAY_RELEASE_SHA: preserve(),
      REDIS_RESOURCE_ID: preserve(),
      REDIS_URL: preserve(),
      SENTRY_ENABLED: preserve(),
      STORAGE_RESOURCE_ID: preserve(),
      VOICE_MODE_ENABLED: preserve(),
      WIDGET_PREVIEW_ORIGINS_JSON: preserve(),
      WORKER_SCHEDULERS_ENABLED: preserve(),
    },
  })
  const stagingDashboard = service('staging-dashboard', {
    source: github('tomschoenekase-dotcom/pathfinder', {
      branch: 'codex/pathfinder-v2-staging',
      checkSuites: false,
    }),
    build: {
      builder: 'DOCKERFILE',
      dockerfilePath: 'Dockerfile',
    },
    deploy: {
      restartPolicyType: 'ON_FAILURE',
      restartPolicyMaxRetries: 3,
    },
    replicas: { 'europe-west4-drams3a': 1 },
    domains: ['app.staging.torchiko.com'],
    env: {
      BILLING_ENTITLEMENT_ENFORCEMENT_ENABLED: preserve(),
      BILLING_GRACE_PERIOD_DAYS: preserve(),
      CLERK_PUBLISHABLE_KEY: preserve(),
      CLERK_SECRET_KEY: preserve(),
      CLERK_WEBHOOK_SECRET: preserve(),
      CRM_AUTONOMOUS_OUTREACH_ENABLED: preserve(),
      CRM_PROSPECT_OUTREACH_ENABLED: preserve(),
      DASHBOARD_URL: preserve(),
      DATABASE_RESOURCE_ID: preserve(),
      DATABASE_URL: preserve(),
      DIRECT_DATABASE_URL: preserve(),
      EMBEDDING_DISPATCH_ENABLED: preserve(),
      EMBED_PREVIEW_ENABLED: preserve(),
      EVALUATION_RUNNER_ENABLED: preserve(),
      FOUNDER_ABSENCE_OBSERVER_ENABLED: preserve(),
      GENERALIZED_CONTENT_CAPABILITIES_ENABLED: preserve(),
      GENERATION_DISPATCH_ENABLED: preserve(),
      GENERATION_RECOVERY_ENABLED: preserve(),
      INTAKE_CLAMAV_HOST: preserve(),
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: preserve(),
      NEXT_PUBLIC_PWA_ENABLED: preserve(),
      NEXT_PUBLIC_SENTRY_ENABLED: preserve(),
      NEXT_PUBLIC_SENTRY_ENVIRONMENT: preserve(),
      NEXT_PUBLIC_WEB_URL: preserve(),
      OPENAI_API_KEY: preserve(),
      OUTBOUND_PROVIDER_WORKERS_ENABLED: preserve(),
      PATHFINDER_ALLOW_STAGING_MIGRATIONS: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATABASE_HOST: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATABASE_NAME: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATABASE_RESOURCE: preserve(),
      PATHFINDER_CONFIRM_STAGING_DATA_POLICY: preserve(),
      PATHFINDER_CONFIRM_STAGING_DIRECT_DATABASE_HOST: preserve(),
      PATHFINDER_RELEASE_SHA: preserve(),
      PATHFINDER_STAGING_DATABASE_RESOURCE: preserve(),
      PATHFINDER_STAGING_LOCAL_UPLOAD_APPROVAL: preserve(),
      PATHFINDER_STAGING_SPEND_CEILING_USD: preserve(),
      PROSPECT_OUTREACH_DELIVERY_ENABLED: preserve(),
      RAILWAY_ENVIRONMENT: preserve(),
      RAILWAY_RELEASE_SHA: preserve(),
      REDIS_RESOURCE_ID: preserve(),
      REDIS_URL: preserve(),
      SENTRY_ENABLED: preserve(),
      STORAGE_ACCESS_KEY_ID: preserve(),
      STORAGE_BUCKET: preserve(),
      STORAGE_ENDPOINT: preserve(),
      STORAGE_REGION: preserve(),
      STORAGE_RESOURCE_ID: preserve(),
      STORAGE_SECRET_ACCESS_KEY: preserve(),
      STRIPE_ACCOUNT_NAMESPACE: preserve(),
      STRIPE_BILLING_UI_ENABLED: preserve(),
      STRIPE_CANCELLATION_ENABLED: preserve(),
      STRIPE_CATALOG_JSON: preserve(),
      STRIPE_CHECKOUT_ENABLED: preserve(),
      STRIPE_CUSTOMER_PORTAL_CONFIGURATION_ID: preserve(),
      STRIPE_CUSTOMER_PORTAL_ENABLED: preserve(),
      STRIPE_LIVE_MODE_ALLOWED: preserve(),
      STRIPE_MODE: preserve(),
      STRIPE_RECONCILIATION_ENABLED: preserve(),
      STRIPE_SECRET_KEY: preserve(),
      STRIPE_WEBHOOK_PROCESSING_ENABLED: preserve(),
      STRIPE_WEBHOOK_SECRET: preserve(),
      VOICE_MODE_ENABLED: preserve(),
      WIDGET_PREVIEW_ORIGINS_JSON: preserve(),
      WORKER_SCHEDULERS_ENABLED: preserve(),
    },
  })

  return project('serene-inspiration', {
    resources: [
      clamav,
      pgvector,
      stagingWorkers,
      stagingWeb,
      stagingDashboard,
      Redis5Vrb,
      redisVolumePu8X,
      pgvectorVolume,
      reservedTote,
    ],
  })
})
