ALTER TYPE "AgentOutcomeSignalKind" ADD VALUE 'ROLLBACK';
ALTER TYPE "AgentOutcomeSignalKind" ADD VALUE 'POLICY_VIOLATION';
ALTER TYPE "AgentOutcomeSignalKind" ADD VALUE 'CONFIDENCE_CALIBRATION';

CREATE TYPE "AgentOutcomeSeverity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
