import { createHash } from 'node:crypto'

const SECRET_NAME =
  /(?:SECRET|TOKEN|PASSWORD|PRIVATE_KEY|ACCESS_KEY|API_KEY|DATABASE_URL|REDIS_URL|DSN)$/u

function sha256(value) {
  return createHash('sha256').update(value).digest('hex')
}

export function collectEnvironmentNames(source) {
  const names = new Set()
  for (const line of source.split(/\r?\n/u)) {
    const match = line.match(/^\s*(?:#\s*)?([A-Z][A-Z0-9_]*)=/u)
    if (match) names.add(match[1])
  }
  return [...names].sort()
}

export function classifyEnvironmentName(name) {
  if (name.startsWith('NEXT_PUBLIC_')) return 'browser-visible'
  if (SECRET_NAME.test(name)) return 'secret/server-only'
  if (name.endsWith('_ENABLED') || name.endsWith('_MODE')) return 'policy/feature gate'
  if (name.endsWith('_RESOURCE_ID') || name.endsWith('_RELEASE') || name.endsWith('_SHA')) {
    return 'deployment identity'
  }
  return 'server configuration'
}

export function classifyScript(name) {
  if (name.startsWith('verify:')) return 'verification'
  if (name.startsWith('test:')) return 'testing'
  if (name.startsWith('db:')) return 'database'
  if (name.startsWith('local-staging:') || name.startsWith('staging:')) return 'staging'
  if (name.startsWith('golden-venue:')) return 'golden venue'
  if (name.startsWith('characters:')) return 'character assets'
  if (name.startsWith('embedding:') || name.startsWith('jobs:')) return 'operations'
  return 'core development'
}

export function renderRepositoryIndex({ packageJson, environmentSource }) {
  const scripts = Object.entries(packageJson.scripts ?? {}).sort(([left], [right]) =>
    left.localeCompare(right),
  )
  const environmentNames = collectEnvironmentNames(environmentSource)
  const fingerprint = sha256(
    JSON.stringify({ scripts, environmentNames, packageManager: packageJson.packageManager }),
  )
  const scriptRows = scripts
    .map(
      ([name, command]) =>
        `| \`pnpm ${name}\` | ${classifyScript(name)} | \`${String(command).replaceAll('|', '\\|')}\` |`,
    )
    .join('\n')
  const environmentRows = environmentNames
    .map((name) => `| \`${name}\` | ${classifyEnvironmentName(name)} |`)
    .join('\n')

  return `# Repository command and configuration index

> **Migration instruction status: STAGING-ONLY AUTHORIZED — PRODUCTION COMMANDS REMAIN STOPPED.**

> Generated by \`pnpm repository:index\`. Do not edit by hand. Source fingerprint: \`${fingerprint}\`.

This is a discovery index, not an activation guide. Commands retain their checked-in safety gates. Environment values are intentionally omitted; \`packages/config/src/env.ts\` and its tests are authoritative for runtime admission.

## Root commands

| Command | Area | Implementation |
| --- | --- | --- |
${scriptRows}

## Documented environment surface

The names below come from \`.env.example\`, including commented examples. No configured values or credentials are copied into this document.

| Variable | Handling class |
| --- | --- |
${environmentRows}
`
}
