import { SUPPORTED_CHAT_LANGUAGES, type SupportedChatLanguage } from '@pathfinder/api/schemas'

type VisitorUiCopy = {
  shell: readonly [
    selectLanguage: string,
    back: string,
    newConversation: string,
    conversation: string,
    you: string,
    askQuestion: string,
    reconnectToSend: string,
    sendingMessage: string,
    sendMessage: string,
    send: string,
    isResponding: string,
    aiGuidanceLabel: string,
    aiGuidance: string,
    poweredBy: string,
    offlineTitle: string,
    offlineBody: string,
    backOnlineTitle: string,
    backOnlineBody: string,
    rateAnswer: string,
    helpfulQuestion: string,
    helpful: string,
    notHelpful: string,
    transientFailure: string,
  ]
  location: readonly [
    checkingTitle: string,
    checkingDescription: string,
    deniedTitle: string,
    deniedDescription: string,
    deniedAction: string,
    promptTitle: string,
    promptDescription: string,
    promptAction: string,
  ]
  route: readonly [
    toggle: string,
    start: string,
    destination: string,
    accessibleOnly: string,
    finding: string,
    find: string,
    chooseDifferent: string,
    noAccessibleRoute: string,
    noRoute: string,
    accessibleNote: string,
    reviewedRoute: string,
    partialGuidance: string,
    equivalentRoute: string,
    continueTo: (destination: string, connection: string) => string,
  ]
  place: readonly [
    showDetails: string,
    hideDetails: string,
    area: string,
    hours: string,
    directions: string,
    directionsTo: (name: string) => string,
  ]
}

type VisitorStateCopy = readonly [
  loading: string,
  venueUnavailable: string,
  guideTemporarilyUnavailable: string,
  temporarilyUnavailableBody: string,
  tryAgain: string,
  backToHome: string,
]

export function getVisitorTextPresentation(language: SupportedChatLanguage) {
  const supported = SUPPORTED_CHAT_LANGUAGES.find((candidate) => candidate.label === language)
  return {
    code: supported?.code ?? 'en',
    direction: supported?.code === 'ar' ? ('rtl' as const) : ('ltr' as const),
  }
}

const COPY: Record<SupportedChatLanguage, VisitorUiCopy> = {
  English: {
    shell: [
      'Select language',
      'Back',
      'New conversation',
      'Conversation',
      'You',
      'Ask a question',
      'Reconnect to send message',
      'Sending message',
      'Send message',
      'Send',
      'is responding',
      'AI guidance',
      'AI-generated answers can be wrong. Verify important details with venue staff, and do not share sensitive information.',
      'Powered by',
      "You're offline",
      'Keep typing—your draft stays on this screen. Reconnect before sending.',
      'Back online',
      'You can send your draft. If a message needs attention, use its retry or check action.',
      'Rate this answer',
      'Was this helpful?',
      'Helpful',
      'Not helpful',
      'The guide could not start this message. Wait a moment, then send it again as a new message.',
    ],
    location: [
      'Checking location…',
      'You can still ask general questions while we wait for your device position.',
      'Location access denied',
      'General questions still work. Enable location in your browser settings for distance-aware answers.',
      'Try again',
      'Allow location for better answers',
      'General questions work without it. Share location to learn what is nearby.',
      'Share location',
    ],
    route: [
      'Plan a route',
      'Start',
      'Destination',
      'Use only connections marked accessible',
      'Finding route…',
      'Find route',
      'Choose two different locations.',
      'No reviewed accessible route is available between those locations.',
      'No reviewed route is available between those locations.',
      'Uses only connections the venue marked accessible. Confirm critical access needs with venue staff.',
      'Venue-reviewed route',
      'Some steps do not have landmark directions. Follow the named areas and ask venue staff if the path is unclear.',
      'Another reviewed route is available. This option has the clearest available step guidance.',
      (destination, connection) => `Continue to ${destination} via ${connection}.`,
    ],
    place: [
      'Show details for',
      'Hide details for',
      'Area',
      'Hours',
      'Get directions',
      (name) => `Get directions to ${name}`,
    ],
  },
  Español: {
    shell: [
      'Seleccionar idioma',
      'Volver',
      'Nueva conversación',
      'Conversación',
      'Tú',
      'Haz una pregunta',
      'Vuelve a conectarte para enviar el mensaje',
      'Enviando mensaje',
      'Enviar mensaje',
      'Enviar',
      'está respondiendo',
      'Orientación de IA',
      'Las respuestas generadas por IA pueden ser incorrectas. Confirma los detalles importantes con el personal y no compartas información sensible.',
      'Con tecnología de',
      'Estás sin conexión',
      'Sigue escribiendo: tu borrador permanecerá en esta pantalla. Vuelve a conectarte antes de enviarlo.',
      'Conexión restablecida',
      'Ya puedes enviar tu borrador. Si un mensaje requiere atención, usa la opción para reintentar o comprobar.',
      'Valorar esta respuesta',
      '¿Te resultó útil?',
      'Útil',
      'No útil',
      'La guía no pudo iniciar este mensaje. Espera un momento y envíalo de nuevo como un mensaje nuevo.',
    ],
    location: [
      'Comprobando la ubicación…',
      'Puedes seguir haciendo preguntas generales mientras esperamos la ubicación de tu dispositivo.',
      'Acceso a la ubicación denegado',
      'Las preguntas generales siguen funcionando. Activa la ubicación en el navegador para obtener respuestas basadas en la distancia.',
      'Intentar de nuevo',
      'Permite la ubicación para obtener mejores respuestas',
      'Las preguntas generales funcionan sin ella. Comparte tu ubicación para saber qué hay cerca.',
      'Compartir ubicación',
    ],
    route: [
      'Planificar una ruta',
      'Inicio',
      'Destino',
      'Usar solo conexiones marcadas como accesibles',
      'Buscando ruta…',
      'Buscar ruta',
      'Elige dos ubicaciones diferentes.',
      'No hay una ruta accesible revisada entre esas ubicaciones.',
      'No hay una ruta revisada entre esas ubicaciones.',
      'Usa solo conexiones que el lugar marcó como accesibles. Confirma las necesidades de acceso importantes con el personal.',
      'Ruta revisada por el lugar',
      'Algunos pasos no incluyen indicaciones con puntos de referencia. Sigue las zonas indicadas y pregunta al personal si el camino no está claro.',
      'Hay otra ruta revisada disponible. Esta opción ofrece las indicaciones más claras disponibles.',
      (destination, connection) => `Continúa hasta ${destination} por ${connection}.`,
    ],
    place: [
      'Mostrar detalles de',
      'Ocultar detalles de',
      'Zona',
      'Horario',
      'Cómo llegar',
      (name) => `Cómo llegar a ${name}`,
    ],
  },
  Français: {
    shell: [
      'Sélectionner la langue',
      'Retour',
      'Nouvelle conversation',
      'Conversation',
      'Vous',
      'Poser une question',
      'Reconnectez-vous pour envoyer le message',
      'Envoi du message',
      'Envoyer le message',
      'Envoyer',
      'répond',
      'Conseils de l’IA',
      'Les réponses générées par l’IA peuvent être erronées. Vérifiez les détails importants auprès du personnel et ne partagez pas d’informations sensibles.',
      'Propulsé par',
      'Vous êtes hors ligne',
      'Continuez à écrire : votre brouillon reste sur cet écran. Reconnectez-vous avant de l’envoyer.',
      'Connexion rétablie',
      'Vous pouvez envoyer votre brouillon. Si un message nécessite votre attention, utilisez l’action de nouvelle tentative ou de vérification.',
      'Évaluer cette réponse',
      'Cette réponse vous a-t-elle aidé ?',
      'Utile',
      'Pas utile',
      'Le guide n’a pas pu démarrer ce message. Patientez un instant, puis envoyez-le à nouveau comme nouveau message.',
    ],
    location: [
      'Vérification de la position…',
      'Vous pouvez continuer à poser des questions générales pendant que nous attendons la position de votre appareil.',
      'Accès à la position refusé',
      'Les questions générales fonctionnent toujours. Activez la position dans votre navigateur pour des réponses fondées sur la distance.',
      'Réessayer',
      'Autorisez la position pour de meilleures réponses',
      'Les questions générales fonctionnent sans elle. Partagez votre position pour découvrir ce qui se trouve à proximité.',
      'Partager la position',
    ],
    route: [
      'Planifier un itinéraire',
      'Départ',
      'Destination',
      'Utiliser uniquement les liaisons indiquées comme accessibles',
      'Recherche de l’itinéraire…',
      'Trouver l’itinéraire',
      'Choisissez deux lieux différents.',
      'Aucun itinéraire accessible vérifié n’est disponible entre ces lieux.',
      'Aucun itinéraire vérifié n’est disponible entre ces lieux.',
      'Utilise uniquement les liaisons indiquées comme accessibles. Confirmez les besoins d’accès importants auprès du personnel.',
      'Itinéraire vérifié par le lieu',
      'Certaines étapes n’ont pas d’indications avec des repères. Suivez les zones nommées et demandez au personnel si le chemin n’est pas clair.',
      'Un autre itinéraire vérifié est disponible. Cette option offre les indications les plus claires disponibles.',
      (destination, connection) => `Continuez vers ${destination} via ${connection}.`,
    ],
    place: [
      'Afficher les détails de',
      'Masquer les détails de',
      'Zone',
      'Horaires',
      'Itinéraire',
      (name) => `Itinéraire vers ${name}`,
    ],
  },
  Deutsch: {
    shell: [
      'Sprache auswählen',
      'Zurück',
      'Neue Unterhaltung',
      'Unterhaltung',
      'Sie',
      'Frage stellen',
      'Zum Senden erneut verbinden',
      'Nachricht wird gesendet',
      'Nachricht senden',
      'Senden',
      'antwortet',
      'KI-Hinweis',
      'KI-generierte Antworten können falsch sein. Bestätigen Sie wichtige Angaben beim Personal und teilen Sie keine vertraulichen Informationen.',
      'Bereitgestellt von',
      'Sie sind offline',
      'Schreiben Sie weiter – Ihr Entwurf bleibt auf diesem Bildschirm. Stellen Sie vor dem Senden die Verbindung wieder her.',
      'Wieder online',
      'Sie können Ihren Entwurf senden. Wenn eine Nachricht Aufmerksamkeit benötigt, verwenden Sie die Aktion zum Wiederholen oder Prüfen.',
      'Diese Antwort bewerten',
      'War das hilfreich?',
      'Hilfreich',
      'Nicht hilfreich',
      'Der Guide konnte diese Nachricht nicht starten. Warten Sie einen Moment und senden Sie sie dann als neue Nachricht erneut.',
    ],
    location: [
      'Standort wird geprüft…',
      'Sie können weiterhin allgemeine Fragen stellen, während wir auf den Gerätestandort warten.',
      'Standortzugriff abgelehnt',
      'Allgemeine Fragen funktionieren weiterhin. Aktivieren Sie den Standort im Browser für entfernungsbezogene Antworten.',
      'Erneut versuchen',
      'Standort für bessere Antworten freigeben',
      'Allgemeine Fragen funktionieren auch ohne Standort. Teilen Sie ihn, um Orte in der Nähe zu finden.',
      'Standort teilen',
    ],
    route: [
      'Route planen',
      'Start',
      'Ziel',
      'Nur als barrierefrei markierte Verbindungen verwenden',
      'Route wird gesucht…',
      'Route finden',
      'Wählen Sie zwei verschiedene Orte.',
      'Zwischen diesen Orten ist keine geprüfte barrierefreie Route verfügbar.',
      'Zwischen diesen Orten ist keine geprüfte Route verfügbar.',
      'Verwendet nur als barrierefrei markierte Verbindungen. Klären Sie wichtige Zugangsbedürfnisse mit dem Personal.',
      'Vom Veranstaltungsort geprüfte Route',
      'Einige Schritte enthalten keine Orientierungspunkte. Folgen Sie den benannten Bereichen und fragen Sie das Personal, wenn der Weg unklar ist.',
      'Eine weitere geprüfte Route ist verfügbar. Diese Option bietet die klarsten verfügbaren Schrittangaben.',
      (destination, connection) => `Weiter zu ${destination} über ${connection}.`,
    ],
    place: [
      'Details anzeigen für',
      'Details ausblenden für',
      'Bereich',
      'Öffnungszeiten',
      'Route',
      (name) => `Route zu ${name}`,
    ],
  },
  Italiano: {
    shell: [
      'Seleziona lingua',
      'Indietro',
      'Nuova conversazione',
      'Conversazione',
      'Tu',
      'Fai una domanda',
      'Riconnettiti per inviare il messaggio',
      'Invio del messaggio',
      'Invia messaggio',
      'Invia',
      'sta rispondendo',
      'Indicazioni sull’IA',
      'Le risposte generate dall’IA possono essere errate. Verifica i dettagli importanti con il personale e non condividere informazioni sensibili.',
      'Offerto da',
      'Sei offline',
      'Continua a scrivere: la bozza resta su questa schermata. Riconnettiti prima di inviarla.',
      'Di nuovo online',
      'Puoi inviare la bozza. Se un messaggio richiede attenzione, usa l’azione per riprovare o verificare.',
      'Valuta questa risposta',
      'È stato utile?',
      'Utile',
      'Non utile',
      'La guida non è riuscita ad avviare questo messaggio. Attendi un momento, quindi invialo di nuovo come nuovo messaggio.',
    ],
    location: [
      'Verifica della posizione…',
      'Puoi continuare a fare domande generali mentre attendiamo la posizione del dispositivo.',
      'Accesso alla posizione negato',
      'Le domande generali funzionano comunque. Attiva la posizione nel browser per risposte basate sulla distanza.',
      'Riprova',
      'Consenti la posizione per risposte migliori',
      'Le domande generali funzionano senza posizione. Condividila per scoprire cosa c’è nelle vicinanze.',
      'Condividi posizione',
    ],
    route: [
      'Pianifica un percorso',
      'Partenza',
      'Destinazione',
      'Usa solo collegamenti contrassegnati come accessibili',
      'Ricerca del percorso…',
      'Trova percorso',
      'Scegli due luoghi diversi.',
      'Non è disponibile un percorso accessibile verificato tra questi luoghi.',
      'Non è disponibile un percorso verificato tra questi luoghi.',
      'Usa solo collegamenti contrassegnati come accessibili. Conferma le esigenze importanti con il personale.',
      'Percorso verificato dalla struttura',
      'Alcuni passaggi non includono indicazioni con punti di riferimento. Segui le aree indicate e chiedi al personale se il percorso non è chiaro.',
      'È disponibile un altro percorso verificato. Questa opzione offre le indicazioni più chiare disponibili.',
      (destination, connection) => `Prosegui verso ${destination} tramite ${connection}.`,
    ],
    place: [
      'Mostra dettagli per',
      'Nascondi dettagli per',
      'Area',
      'Orari',
      'Indicazioni',
      (name) => `Indicazioni per ${name}`,
    ],
  },
  Português: {
    shell: [
      'Selecionar idioma',
      'Voltar',
      'Nova conversa',
      'Conversa',
      'Você',
      'Faça uma pergunta',
      'Reconecte-se para enviar a mensagem',
      'Enviando mensagem',
      'Enviar mensagem',
      'Enviar',
      'está respondendo',
      'Orientação de IA',
      'As respostas geradas por IA podem estar erradas. Confirme detalhes importantes com a equipe e não compartilhe informações sensíveis.',
      'Desenvolvido por',
      'Você está offline',
      'Continue digitando: seu rascunho permanece nesta tela. Reconecte-se antes de enviar.',
      'Conexão restabelecida',
      'Você pode enviar o rascunho. Se uma mensagem precisar de atenção, use a ação de tentar novamente ou verificar.',
      'Avaliar esta resposta',
      'Isso foi útil?',
      'Útil',
      'Não foi útil',
      'O guia não conseguiu iniciar esta mensagem. Aguarde um momento e envie-a novamente como uma nova mensagem.',
    ],
    location: [
      'Verificando a localização…',
      'Você ainda pode fazer perguntas gerais enquanto aguardamos a localização do dispositivo.',
      'Acesso à localização negado',
      'As perguntas gerais continuam funcionando. Ative a localização no navegador para respostas baseadas em distância.',
      'Tentar novamente',
      'Permita a localização para respostas melhores',
      'As perguntas gerais funcionam sem ela. Compartilhe a localização para descobrir o que está por perto.',
      'Compartilhar localização',
    ],
    route: [
      'Planejar uma rota',
      'Início',
      'Destino',
      'Usar somente conexões marcadas como acessíveis',
      'Procurando rota…',
      'Encontrar rota',
      'Escolha dois locais diferentes.',
      'Não há uma rota acessível revisada entre esses locais.',
      'Não há uma rota revisada entre esses locais.',
      'Usa somente conexões marcadas como acessíveis. Confirme necessidades importantes de acesso com a equipe.',
      'Rota revisada pelo local',
      'Algumas etapas não têm orientações por pontos de referência. Siga as áreas indicadas e pergunte à equipe se o caminho não estiver claro.',
      'Há outra rota revisada disponível. Esta opção oferece as orientações mais claras disponíveis.',
      (destination, connection) => `Continue até ${destination} por ${connection}.`,
    ],
    place: [
      'Mostrar detalhes de',
      'Ocultar detalhes de',
      'Área',
      'Horários',
      'Como chegar',
      (name) => `Como chegar a ${name}`,
    ],
  },
  中文: {
    shell: [
      '选择语言',
      '返回',
      '新对话',
      '对话',
      '您',
      '提出问题',
      '重新连接后发送消息',
      '正在发送消息',
      '发送消息',
      '发送',
      '正在回复',
      'AI 使用提示',
      'AI 生成的回答可能有误。重要信息请向场所工作人员核实，并且不要分享敏感信息。',
      '技术支持',
      '您已离线',
      '您可以继续输入，草稿会保留在此屏幕上。请重新连接后再发送。',
      '已恢复连接',
      '现在可以发送草稿。如果消息需要处理，请使用重试或检查操作。',
      '评价此回答',
      '这个回答有帮助吗？',
      '有帮助',
      '没有帮助',
      '导览无法开始处理此消息。请稍候，然后将其作为新消息重新发送。',
    ],
    location: [
      '正在检查位置…',
      '等待设备位置时，您仍可询问一般问题。',
      '位置访问已拒绝',
      '一般问题仍可使用。请在浏览器设置中启用位置，以获取基于距离的回答。',
      '重试',
      '允许位置以获得更好的回答',
      '不共享位置也可询问一般问题。共享位置可了解附近地点。',
      '共享位置',
    ],
    route: [
      '规划路线',
      '起点',
      '目的地',
      '仅使用标记为无障碍的连接',
      '正在查找路线…',
      '查找路线',
      '请选择两个不同的地点。',
      '这些地点之间没有经过审核的无障碍路线。',
      '这些地点之间没有经过审核的路线。',
      '仅使用场所标记为无障碍的连接。重要的无障碍需求请向工作人员确认。',
      '场所已审核路线',
      '部分步骤没有地标指引。请按所列区域前行；如果路线不清楚，请询问工作人员。',
      '另有一条已审核路线可用。此选项提供现有最清晰的分步指引。',
      (destination, connection) => `经由${connection}继续前往${destination}。`,
    ],
    place: [
      '显示详情：',
      '隐藏详情：',
      '区域',
      '时间',
      '获取路线',
      (name) => `获取前往${name}的路线`,
    ],
  },
  日本語: {
    shell: [
      '言語を選択',
      '戻る',
      '新しい会話',
      '会話',
      'あなた',
      '質問する',
      '再接続してメッセージを送信',
      'メッセージを送信中',
      'メッセージを送信',
      '送信',
      'が回答中です',
      'AI 利用上の注意',
      'AI が生成した回答は誤っている場合があります。重要な情報は施設スタッフに確認し、機密情報を共有しないでください。',
      '提供',
      'オフラインです',
      '入力を続けても下書きはこの画面に残ります。送信前に再接続してください。',
      'オンラインに戻りました',
      '下書きを送信できます。メッセージに対応が必要な場合は、再試行または確認操作を使用してください。',
      'この回答を評価',
      '役に立ちましたか？',
      '役に立った',
      '役に立たなかった',
      'ガイドはこのメッセージの処理を開始できませんでした。少し待ってから、新しいメッセージとしてもう一度送信してください。',
    ],
    location: [
      '位置情報を確認しています…',
      '端末の位置を待つ間も、一般的な質問はできます。',
      '位置情報へのアクセスが拒否されました',
      '一般的な質問は引き続き利用できます。距離に基づく回答には、ブラウザ設定で位置情報を有効にしてください。',
      'もう一度試す',
      'より良い回答のため位置情報を許可',
      '位置情報がなくても一般的な質問はできます。共有すると近くの場所が分かります。',
      '位置情報を共有',
    ],
    route: [
      'ルートを計画',
      '出発地',
      '目的地',
      'バリアフリーと表示された経路のみ使用',
      'ルートを検索中…',
      'ルートを検索',
      '異なる2つの場所を選んでください。',
      'この2地点間には確認済みのバリアフリールートがありません。',
      'この2地点間には確認済みのルートがありません。',
      '施設がバリアフリーと表示した経路のみを使います。重要な要件はスタッフに確認してください。',
      '施設確認済みのルート',
      '一部の手順には目印を使った案内がありません。表示されたエリアをたどり、経路が不明な場合はスタッフに確認してください。',
      '別の確認済みルートもあります。この案内は利用可能な中で最も明確な手順を示しています。',
      (destination, connection) => `${connection}を通って${destination}へ進みます。`,
    ],
    place: [
      '詳細を表示：',
      '詳細を隠す：',
      'エリア',
      '時間',
      '道順を見る',
      (name) => `${name}への道順を見る`,
    ],
  },
  한국어: {
    shell: [
      '언어 선택',
      '뒤로',
      '새 대화',
      '대화',
      '나',
      '질문하기',
      '다시 연결한 후 메시지 보내기',
      '메시지 보내는 중',
      '메시지 보내기',
      '보내기',
      '답변 중',
      'AI 안내',
      'AI가 생성한 답변은 틀릴 수 있습니다. 중요한 내용은 시설 직원에게 확인하고 민감한 정보를 공유하지 마세요.',
      '제공',
      '오프라인 상태입니다',
      '계속 입력해도 초안은 이 화면에 남습니다. 보내기 전에 다시 연결하세요.',
      '다시 온라인 상태입니다',
      '이제 초안을 보낼 수 있습니다. 메시지에 확인이 필요하면 다시 시도 또는 확인 작업을 사용하세요.',
      '이 답변 평가',
      '도움이 되었나요?',
      '도움이 됨',
      '도움이 안 됨',
      '가이드가 이 메시지 처리를 시작하지 못했습니다. 잠시 기다린 후 새 메시지로 다시 보내세요.',
    ],
    location: [
      '위치 확인 중…',
      '기기 위치를 기다리는 동안에도 일반 질문을 할 수 있습니다.',
      '위치 접근이 거부됨',
      '일반 질문은 계속 사용할 수 있습니다. 거리 기반 답변을 받으려면 브라우저 설정에서 위치를 켜세요.',
      '다시 시도',
      '더 나은 답변을 위해 위치 허용',
      '위치 없이도 일반 질문은 가능합니다. 위치를 공유하면 주변 장소를 알 수 있습니다.',
      '위치 공유',
    ],
    route: [
      '경로 계획',
      '출발지',
      '목적지',
      '접근 가능으로 표시된 연결만 사용',
      '경로 찾는 중…',
      '경로 찾기',
      '서로 다른 두 장소를 선택하세요.',
      '이 장소들 사이에 검토된 접근 가능 경로가 없습니다.',
      '이 장소들 사이에 검토된 경로가 없습니다.',
      '시설이 접근 가능으로 표시한 연결만 사용합니다. 중요한 요구 사항은 직원에게 확인하세요.',
      '시설 검토 경로',
      '일부 단계에는 랜드마크 안내가 없습니다. 표시된 구역을 따라가고 경로가 불분명하면 직원에게 문의하세요.',
      '다른 검토된 경로도 있습니다. 이 옵션은 이용 가능한 단계 안내 중 가장 명확한 안내를 제공합니다.',
      (destination, connection) => `${connection}을(를) 통해 ${destination}(으)로 이동하세요.`,
    ],
    place: [
      '세부 정보 보기:',
      '세부 정보 숨기기:',
      '구역',
      '운영 시간',
      '길 안내',
      (name) => `${name} 길 안내`,
    ],
  },
  العربية: {
    shell: [
      'اختيار اللغة',
      'رجوع',
      'محادثة جديدة',
      'المحادثة',
      'أنت',
      'اطرح سؤالًا',
      'أعد الاتصال لإرسال الرسالة',
      'جارٍ إرسال الرسالة',
      'إرسال الرسالة',
      'إرسال',
      'يجيب الآن',
      'إرشادات الذكاء الاصطناعي',
      'قد تكون الإجابات التي ينشئها الذكاء الاصطناعي خاطئة. تحقّق من التفاصيل المهمة مع طاقم المكان ولا تشارك معلومات حساسة.',
      'بدعم من',
      'أنت غير متصل',
      'يمكنك متابعة الكتابة وستبقى المسودة على هذه الشاشة. أعد الاتصال قبل الإرسال.',
      'عاد الاتصال',
      'يمكنك إرسال المسودة الآن. إذا احتاجت رسالة إلى متابعة، فاستخدم إجراء إعادة المحاولة أو التحقق.',
      'تقييم هذه الإجابة',
      'هل كانت هذه الإجابة مفيدة؟',
      'مفيدة',
      'غير مفيدة',
      'تعذر على الدليل بدء معالجة هذه الرسالة. انتظر لحظة ثم أرسلها مرة أخرى كرسالة جديدة.',
    ],
    location: [
      'جارٍ التحقق من الموقع…',
      'لا يزال بإمكانك طرح أسئلة عامة أثناء انتظار موقع جهازك.',
      'تم رفض الوصول إلى الموقع',
      'تظل الأسئلة العامة متاحة. فعّل الموقع في إعدادات المتصفح للحصول على إجابات تعتمد على المسافة.',
      'المحاولة مرة أخرى',
      'اسمح بالموقع للحصول على إجابات أفضل',
      'تعمل الأسئلة العامة بدونه. شارك موقعك لمعرفة ما هو قريب.',
      'مشاركة الموقع',
    ],
    route: [
      'تخطيط مسار',
      'البداية',
      'الوجهة',
      'استخدام الوصلات المحددة بأنها ميسّرة فقط',
      'جارٍ العثور على المسار…',
      'العثور على مسار',
      'اختر موقعين مختلفين.',
      'لا يوجد مسار ميسّر ومراجع بين هذين الموقعين.',
      'لا يوجد مسار مراجع بين هذين الموقعين.',
      'يستخدم فقط الوصلات المحددة بأنها ميسّرة. أكّد احتياجات الوصول المهمة مع الطاقم.',
      'مسار راجعه المكان',
      'لا تتضمن بعض الخطوات إرشادات بالمعالم. اتبع أسماء المناطق واسأل الطاقم إذا لم يكن المسار واضحًا.',
      'يتوفر مسار آخر مراجع. يعرض هذا الخيار أوضح إرشادات متاحة للخطوات.',
      (destination, connection) => `تابع إلى ${destination} عبر ${connection}.`,
    ],
    place: [
      'عرض تفاصيل',
      'إخفاء تفاصيل',
      'المنطقة',
      'الساعات',
      'الحصول على الاتجاهات',
      (name) => `الحصول على الاتجاهات إلى ${name}`,
    ],
  },
}

type VisitorRecoveryCopy = readonly [
  ambiguousOutcomeRefreshed: string,
  conflictRefreshed: string,
  conflictHistoryUnknown: string,
  providerUnavailable: string,
  contentUnavailable: string,
  messageRejected: string,
  rateLimited: string,
  outcomeUnknown: string,
  conversationRefreshed: string,
  conversationStillUnknown: string,
  confirmNewConversation: string,
  newConversationFailed: string,
  checkConversation: string,
  retrySameMessage: string,
  prepareSessionFailed: string,
]

const RECOVERY_COPY: Record<SupportedChatLanguage, VisitorRecoveryCopy> = {
  English: [
    'The original message outcome could not be confirmed and will not be retried. The conversation was refreshed; you may send a new message.',
    'The conversation changed while this message was being checked. Review the refreshed conversation before sending a new message.',
    'The conversation changed, but its current history could not be confirmed. Check the conversation before sending a new message.',
    'The guide service is temporarily unavailable. Wait a moment, then send a new message.',
    'This venue content is not available right now. Try again later or ask venue staff.',
    'This message could not be accepted. Review it before sending a new message.',
    'This message was not sent because the guide is busy. Wait a moment, then retry the same message.',
    'The outcome of this message is not confirmed. Retry the same message safely.',
    'Conversation refreshed. The unconfirmed message will not be retried; you may send a new message.',
    'The conversation still could not be confirmed. Try checking again.',
    'Start a new conversation? The current chat will leave this screen, but it will not be deleted from Torchiko records.',
    'We could not start a new conversation in this browser.',
    'Check conversation',
    'Retry same message',
    'We could not prepare the chat session. Please try again.',
  ],
  Español: [
    'No se pudo confirmar el resultado del mensaje original y no se volverá a intentar. La conversación se actualizó; puedes enviar un mensaje nuevo.',
    'La conversación cambió mientras se comprobaba este mensaje. Revisa la conversación actualizada antes de enviar un mensaje nuevo.',
    'La conversación cambió, pero no se pudo confirmar su historial actual. Comprueba la conversación antes de enviar un mensaje nuevo.',
    'El servicio de la guía no está disponible temporalmente. Espera un momento y envía un mensaje nuevo.',
    'El contenido de este lugar no está disponible ahora. Inténtalo más tarde o pregunta al personal.',
    'No se pudo aceptar este mensaje. Revísalo antes de enviar uno nuevo.',
    'El mensaje no se envió porque la guía está ocupada. Espera un momento y vuelve a intentar el mismo mensaje.',
    'No se ha confirmado el resultado de este mensaje. Vuelve a intentar el mismo mensaje de forma segura.',
    'Conversación actualizada. El mensaje sin confirmar no se volverá a intentar; puedes enviar uno nuevo.',
    'Todavía no se pudo confirmar la conversación. Intenta comprobarla de nuevo.',
    '¿Iniciar una conversación nueva? El chat actual saldrá de esta pantalla, pero no se eliminará de los registros de Torchiko.',
    'No pudimos iniciar una conversación nueva en este navegador.',
    'Comprobar conversación',
    'Reintentar el mismo mensaje',
    'No pudimos preparar la sesión de chat. Inténtalo de nuevo.',
  ],
  Français: [
    'Le résultat du message initial n’a pas pu être confirmé et il ne sera pas renvoyé. La conversation a été actualisée ; vous pouvez envoyer un nouveau message.',
    'La conversation a changé pendant la vérification de ce message. Consultez la conversation actualisée avant d’envoyer un nouveau message.',
    'La conversation a changé, mais son historique actuel n’a pas pu être confirmé. Vérifiez la conversation avant d’envoyer un nouveau message.',
    'Le service du guide est temporairement indisponible. Patientez un instant, puis envoyez un nouveau message.',
    'Le contenu de ce lieu n’est pas disponible pour le moment. Réessayez plus tard ou demandez au personnel.',
    'Ce message n’a pas pu être accepté. Vérifiez-le avant d’envoyer un nouveau message.',
    'Ce message n’a pas été envoyé car le guide est occupé. Patientez un instant, puis réessayez le même message.',
    'Le résultat de ce message n’est pas confirmé. Réessayez le même message en toute sécurité.',
    'Conversation actualisée. Le message non confirmé ne sera pas renvoyé ; vous pouvez envoyer un nouveau message.',
    'La conversation n’a toujours pas pu être confirmée. Essayez de la vérifier à nouveau.',
    'Commencer une nouvelle conversation ? Le chat actuel quittera cet écran, mais ne sera pas supprimé des registres Torchiko.',
    'Nous n’avons pas pu démarrer une nouvelle conversation dans ce navigateur.',
    'Vérifier la conversation',
    'Réessayer le même message',
    'Nous n’avons pas pu préparer la session de chat. Veuillez réessayer.',
  ],
  Deutsch: [
    'Das Ergebnis der ursprünglichen Nachricht konnte nicht bestätigt werden und sie wird nicht erneut gesendet. Die Unterhaltung wurde aktualisiert; du kannst eine neue Nachricht senden.',
    'Die Unterhaltung hat sich während der Prüfung dieser Nachricht geändert. Prüfe die aktualisierte Unterhaltung, bevor du eine neue Nachricht sendest.',
    'Die Unterhaltung hat sich geändert, ihr aktueller Verlauf konnte jedoch nicht bestätigt werden. Prüfe die Unterhaltung, bevor du eine neue Nachricht sendest.',
    'Der Guide-Dienst ist vorübergehend nicht verfügbar. Warte einen Moment und sende dann eine neue Nachricht.',
    'Die Inhalte dieses Ortes sind derzeit nicht verfügbar. Versuche es später erneut oder frage das Personal.',
    'Diese Nachricht konnte nicht angenommen werden. Prüfe sie, bevor du eine neue Nachricht sendest.',
    'Diese Nachricht wurde nicht gesendet, weil der Guide beschäftigt ist. Warte einen Moment und versuche dieselbe Nachricht erneut.',
    'Das Ergebnis dieser Nachricht ist nicht bestätigt. Versuche dieselbe Nachricht sicher erneut.',
    'Unterhaltung aktualisiert. Die unbestätigte Nachricht wird nicht erneut gesendet; du kannst eine neue Nachricht senden.',
    'Die Unterhaltung konnte weiterhin nicht bestätigt werden. Versuche erneut, sie zu prüfen.',
    'Eine neue Unterhaltung beginnen? Der aktuelle Chat verlässt diesen Bildschirm, wird aber nicht aus den Torchiko-Datensätzen gelöscht.',
    'In diesem Browser konnte keine neue Unterhaltung gestartet werden.',
    'Unterhaltung prüfen',
    'Dieselbe Nachricht erneut versuchen',
    'Die Chatsitzung konnte nicht vorbereitet werden. Bitte versuche es erneut.',
  ],
  Italiano: [
    'Non è stato possibile confermare l’esito del messaggio originale e non verrà riprovato. La conversazione è stata aggiornata; puoi inviare un nuovo messaggio.',
    'La conversazione è cambiata durante la verifica del messaggio. Controlla la conversazione aggiornata prima di inviare un nuovo messaggio.',
    'La conversazione è cambiata, ma non è stato possibile confermarne la cronologia attuale. Controllala prima di inviare un nuovo messaggio.',
    'Il servizio della guida è temporaneamente non disponibile. Attendi un momento, poi invia un nuovo messaggio.',
    'I contenuti di questo luogo non sono disponibili al momento. Riprova più tardi o chiedi al personale.',
    'Non è stato possibile accettare questo messaggio. Controllalo prima di inviarne uno nuovo.',
    'Il messaggio non è stato inviato perché la guida è occupata. Attendi un momento, poi riprova lo stesso messaggio.',
    'L’esito di questo messaggio non è confermato. Riprova lo stesso messaggio in modo sicuro.',
    'Conversazione aggiornata. Il messaggio non confermato non verrà riprovato; puoi inviarne uno nuovo.',
    'Non è ancora stato possibile confermare la conversazione. Prova a controllarla di nuovo.',
    'Avviare una nuova conversazione? La chat attuale lascerà questa schermata, ma non verrà eliminata dai registri di Torchiko.',
    'Non è stato possibile avviare una nuova conversazione in questo browser.',
    'Controlla conversazione',
    'Riprova lo stesso messaggio',
    'Non è stato possibile preparare la sessione di chat. Riprova.',
  ],
  Português: [
    'Não foi possível confirmar o resultado da mensagem original, e ela não será reenviada. A conversa foi atualizada; você pode enviar uma nova mensagem.',
    'A conversa mudou enquanto esta mensagem era verificada. Confira a conversa atualizada antes de enviar uma nova mensagem.',
    'A conversa mudou, mas não foi possível confirmar o histórico atual. Confira a conversa antes de enviar uma nova mensagem.',
    'O serviço do guia está temporariamente indisponível. Aguarde um momento e envie uma nova mensagem.',
    'O conteúdo deste local não está disponível agora. Tente novamente mais tarde ou pergunte à equipe.',
    'Não foi possível aceitar esta mensagem. Confira-a antes de enviar uma nova mensagem.',
    'A mensagem não foi enviada porque o guia está ocupado. Aguarde um momento e tente novamente a mesma mensagem.',
    'O resultado desta mensagem não foi confirmado. Tente novamente a mesma mensagem com segurança.',
    'Conversa atualizada. A mensagem não confirmada não será reenviada; você pode enviar uma nova mensagem.',
    'Ainda não foi possível confirmar a conversa. Tente verificá-la novamente.',
    'Iniciar uma nova conversa? O chat atual sairá desta tela, mas não será excluído dos registros do Torchiko.',
    'Não foi possível iniciar uma nova conversa neste navegador.',
    'Verificar conversa',
    'Tentar novamente a mesma mensagem',
    'Não foi possível preparar a sessão de chat. Tente novamente.',
  ],
  中文: [
    '无法确认原消息的结果，因此不会重试。对话已刷新；你可以发送一条新消息。',
    '检查此消息时对话已发生变化。发送新消息前，请查看刷新后的对话。',
    '对话已发生变化，但无法确认当前记录。发送新消息前，请检查对话。',
    '导览服务暂时不可用。请稍等片刻，然后发送一条新消息。',
    '此场所的内容目前不可用。请稍后重试或询问场所工作人员。',
    '无法接受此消息。发送新消息前，请先检查内容。',
    '导览正忙，因此消息未发送。请稍等片刻，然后重试同一条消息。',
    '此消息的结果尚未确认。请安全地重试同一条消息。',
    '对话已刷新。不会重试未确认的消息；你可以发送一条新消息。',
    '仍然无法确认对话。请再次检查。',
    '要开始新对话吗？当前聊天将离开此屏幕，但不会从 Torchiko 记录中删除。',
    '无法在此浏览器中开始新对话。',
    '检查对话',
    '重试同一条消息',
    '无法准备聊天会话。请重试。',
  ],
  日本語: [
    '元のメッセージの結果を確認できなかったため、再試行しません。会話を更新しました。新しいメッセージを送信できます。',
    'このメッセージの確認中に会話が変更されました。新しいメッセージを送る前に、更新された会話を確認してください。',
    '会話が変更されましたが、現在の履歴を確認できませんでした。新しいメッセージを送る前に会話を確認してください。',
    'ガイドサービスは一時的に利用できません。少し待ってから新しいメッセージを送信してください。',
    'この施設のコンテンツは現在利用できません。後でもう一度試すか、施設スタッフに確認してください。',
    'このメッセージを受け付けられませんでした。確認してから新しいメッセージを送信してください。',
    'ガイドが混み合っているため、メッセージは送信されませんでした。少し待ってから同じメッセージを再試行してください。',
    'このメッセージの結果は確認されていません。同じメッセージを安全に再試行してください。',
    '会話を更新しました。未確認のメッセージは再試行されません。新しいメッセージを送信できます。',
    '会話をまだ確認できません。もう一度確認してください。',
    '新しい会話を始めますか？現在のチャットはこの画面から離れますが、Torchiko の記録からは削除されません。',
    'このブラウザで新しい会話を開始できませんでした。',
    '会話を確認',
    '同じメッセージを再試行',
    'チャットセッションを準備できませんでした。もう一度お試しください。',
  ],
  한국어: [
    '원래 메시지의 결과를 확인할 수 없어 다시 시도하지 않습니다. 대화를 새로 고쳤으며 새 메시지를 보낼 수 있습니다.',
    '이 메시지를 확인하는 동안 대화가 변경되었습니다. 새 메시지를 보내기 전에 새로 고친 대화를 확인하세요.',
    '대화가 변경되었지만 현재 기록을 확인할 수 없습니다. 새 메시지를 보내기 전에 대화를 확인하세요.',
    '안내 서비스가 일시적으로 제공되지 않습니다. 잠시 기다린 후 새 메시지를 보내세요.',
    '이 장소의 콘텐츠를 현재 이용할 수 없습니다. 나중에 다시 시도하거나 직원에게 문의하세요.',
    '이 메시지를 수락할 수 없습니다. 내용을 확인한 후 새 메시지를 보내세요.',
    '안내가 사용 중이어서 메시지가 전송되지 않았습니다. 잠시 기다린 후 같은 메시지를 다시 시도하세요.',
    '이 메시지의 결과가 확인되지 않았습니다. 같은 메시지를 안전하게 다시 시도하세요.',
    '대화를 새로 고쳤습니다. 확인되지 않은 메시지는 다시 시도하지 않으며 새 메시지를 보낼 수 있습니다.',
    '대화를 아직 확인할 수 없습니다. 다시 확인해 보세요.',
    '새 대화를 시작할까요? 현재 채팅은 이 화면에서 사라지지만 Torchiko 기록에서는 삭제되지 않습니다.',
    '이 브라우저에서 새 대화를 시작할 수 없습니다.',
    '대화 확인',
    '같은 메시지 다시 시도',
    '채팅 세션을 준비할 수 없습니다. 다시 시도하세요.',
  ],
  العربية: [
    'تعذر تأكيد نتيجة الرسالة الأصلية ولن تتم إعادة محاولتها. تم تحديث المحادثة ويمكنك إرسال رسالة جديدة.',
    'تغيّرت المحادثة أثناء التحقق من هذه الرسالة. راجع المحادثة المحدّثة قبل إرسال رسالة جديدة.',
    'تغيّرت المحادثة، لكن تعذر تأكيد سجلّها الحالي. تحقّق من المحادثة قبل إرسال رسالة جديدة.',
    'خدمة الدليل غير متاحة مؤقتًا. انتظر لحظة ثم أرسل رسالة جديدة.',
    'محتوى هذا المكان غير متاح الآن. حاول لاحقًا أو اسأل طاقم المكان.',
    'تعذر قبول هذه الرسالة. راجعها قبل إرسال رسالة جديدة.',
    'لم تُرسل الرسالة لأن الدليل مشغول. انتظر لحظة ثم أعد محاولة الرسالة نفسها.',
    'نتيجة هذه الرسالة غير مؤكدة. أعد محاولة الرسالة نفسها بأمان.',
    'تم تحديث المحادثة. لن تتم إعادة محاولة الرسالة غير المؤكدة ويمكنك إرسال رسالة جديدة.',
    'ما زال يتعذر تأكيد المحادثة. حاول التحقق منها مرة أخرى.',
    'هل تريد بدء محادثة جديدة؟ ستغادر المحادثة الحالية هذه الشاشة، لكنها لن تُحذف من سجلات Torchiko.',
    'تعذر بدء محادثة جديدة في هذا المتصفح.',
    'التحقق من المحادثة',
    'إعادة محاولة الرسالة نفسها',
    'تعذر تجهيز جلسة الدردشة. حاول مرة أخرى.',
  ],
}

const STATE_COPY: Record<SupportedChatLanguage, VisitorStateCopy> = {
  English: [
    'Loading your guide…',
    'Venue unavailable',
    'Guide temporarily unavailable',
    'This venue guide is temporarily unavailable. Please try again later.',
    'Try again',
    'Back to home',
  ],
  Español: [
    'Cargando tu guía…',
    'Lugar no disponible',
    'Guía temporalmente no disponible',
    'Esta guía del lugar no está disponible temporalmente. Inténtalo de nuevo más tarde.',
    'Intentar de nuevo',
    'Volver al inicio',
  ],
  Français: [
    'Chargement de votre guide…',
    'Lieu indisponible',
    'Guide temporairement indisponible',
    'Ce guide du lieu est temporairement indisponible. Réessayez plus tard.',
    'Réessayer',
    'Retour à l’accueil',
  ],
  Deutsch: [
    'Ihr Guide wird geladen…',
    'Ort nicht verfügbar',
    'Guide vorübergehend nicht verfügbar',
    'Dieser Guide ist vorübergehend nicht verfügbar. Versuchen Sie es später erneut.',
    'Erneut versuchen',
    'Zur Startseite',
  ],
  Italiano: [
    'Caricamento della guida…',
    'Luogo non disponibile',
    'Guida temporaneamente non disponibile',
    'Questa guida del luogo è temporaneamente non disponibile. Riprova più tardi.',
    'Riprova',
    'Torna alla home',
  ],
  Português: [
    'Carregando seu guia…',
    'Local indisponível',
    'Guia temporariamente indisponível',
    'Este guia do local está temporariamente indisponível. Tente novamente mais tarde.',
    'Tentar novamente',
    'Voltar ao início',
  ],
  中文: [
    '正在加载导览…',
    '场所不可用',
    '导览暂时不可用',
    '此场所导览暂时不可用。请稍后重试。',
    '重试',
    '返回首页',
  ],
  日本語: [
    'ガイドを読み込んでいます…',
    '施設を利用できません',
    'ガイドは一時的に利用できません',
    'この施設のガイドは一時的に利用できません。後でもう一度お試しください。',
    'もう一度試す',
    'ホームに戻る',
  ],
  한국어: [
    '가이드를 불러오는 중…',
    '장소를 이용할 수 없음',
    '가이드를 일시적으로 이용할 수 없음',
    '이 장소의 가이드를 일시적으로 이용할 수 없습니다. 나중에 다시 시도하세요.',
    '다시 시도',
    '홈으로 돌아가기',
  ],
  العربية: [
    'جارٍ تحميل دليلك…',
    'المكان غير متاح',
    'الدليل غير متاح مؤقتًا',
    'دليل هذا المكان غير متاح مؤقتًا. حاول مرة أخرى لاحقًا.',
    'حاول مرة أخرى',
    'العودة إلى الصفحة الرئيسية',
  ],
}

export function getVisitorUiCopy(language: SupportedChatLanguage = 'English') {
  return COPY[language] ?? COPY.English
}

export function getVisitorRecoveryCopy(language: SupportedChatLanguage = 'English') {
  return RECOVERY_COPY[language] ?? RECOVERY_COPY.English
}

export function getVisitorStateCopy(language: SupportedChatLanguage = 'English') {
  return STATE_COPY[language] ?? STATE_COPY.English
}

export function localizeVisitorShellError(
  message: string | null,
  language: SupportedChatLanguage = 'English',
) {
  if (!message) return message
  if (message === COPY.English.shell[22]) return getVisitorUiCopy(language).shell[22]
  const recoveryIndex = RECOVERY_COPY.English.findIndex((candidate) => candidate === message)
  return recoveryIndex >= 0 ? (getVisitorRecoveryCopy(language)[recoveryIndex] ?? message) : message
}
