import type { SupportedChatLanguage } from '@pathfinder/api/schemas'

type VisitorUiCopy = {
  location: readonly [
    checkingTitle: string,
    checkingDescription: string,
    deniedTitle: string,
    deniedDescription: string,
    deniedAction: string,
    promptTitle: string,
    promptDescription: string,
    promptAction: string,
  ]
  route: readonly [
    toggle: string,
    start: string,
    destination: string,
    accessibleOnly: string,
    finding: string,
    find: string,
    chooseDifferent: string,
    noAccessibleRoute: string,
    noRoute: string,
    accessibleNote: string,
  ]
  place: readonly [
    showDetails: string,
    hideDetails: string,
    area: string,
    hours: string,
    directionsTo: string,
  ]
}

const COPY: Record<SupportedChatLanguage, VisitorUiCopy> = {
  English: {
    location: [
      'Checking location…',
      'You can still ask general questions while we wait for your device position.',
      'Location access denied',
      'General questions still work. Enable location in your browser settings for distance-aware answers.',
      'Try again',
      'Allow location for better answers',
      'General questions work without it. Share location to learn what is nearby.',
      'Share location',
    ],
    route: [
      'Plan a route',
      'Start',
      'Destination',
      'Use only connections marked accessible',
      'Finding route…',
      'Find route',
      'Choose two different locations.',
      'No reviewed accessible route is available between those locations.',
      'No reviewed route is available between those locations.',
      'Uses only connections the venue marked accessible. Confirm critical access needs with venue staff.',
    ],
    place: ['Show details for', 'Hide details for', 'Area', 'Hours', 'Get directions to'],
  },
  Español: {
    location: [
      'Comprobando la ubicación…',
      'Puedes seguir haciendo preguntas generales mientras esperamos la ubicación de tu dispositivo.',
      'Acceso a la ubicación denegado',
      'Las preguntas generales siguen funcionando. Activa la ubicación en el navegador para obtener respuestas basadas en la distancia.',
      'Intentar de nuevo',
      'Permite la ubicación para obtener mejores respuestas',
      'Las preguntas generales funcionan sin ella. Comparte tu ubicación para saber qué hay cerca.',
      'Compartir ubicación',
    ],
    route: [
      'Planificar una ruta',
      'Inicio',
      'Destino',
      'Usar solo conexiones marcadas como accesibles',
      'Buscando ruta…',
      'Buscar ruta',
      'Elige dos ubicaciones diferentes.',
      'No hay una ruta accesible revisada entre esas ubicaciones.',
      'No hay una ruta revisada entre esas ubicaciones.',
      'Usa solo conexiones que el lugar marcó como accesibles. Confirma las necesidades de acceso importantes con el personal.',
    ],
    place: ['Mostrar detalles de', 'Ocultar detalles de', 'Zona', 'Horario', 'Cómo llegar a'],
  },
  Français: {
    location: [
      'Vérification de la position…',
      'Vous pouvez continuer à poser des questions générales pendant que nous attendons la position de votre appareil.',
      'Accès à la position refusé',
      'Les questions générales fonctionnent toujours. Activez la position dans votre navigateur pour des réponses fondées sur la distance.',
      'Réessayer',
      'Autorisez la position pour de meilleures réponses',
      'Les questions générales fonctionnent sans elle. Partagez votre position pour découvrir ce qui se trouve à proximité.',
      'Partager la position',
    ],
    route: [
      'Planifier un itinéraire',
      'Départ',
      'Destination',
      'Utiliser uniquement les liaisons indiquées comme accessibles',
      'Recherche de l’itinéraire…',
      'Trouver l’itinéraire',
      'Choisissez deux lieux différents.',
      'Aucun itinéraire accessible vérifié n’est disponible entre ces lieux.',
      'Aucun itinéraire vérifié n’est disponible entre ces lieux.',
      'Utilise uniquement les liaisons indiquées comme accessibles. Confirmez les besoins d’accès importants auprès du personnel.',
    ],
    place: [
      'Afficher les détails de',
      'Masquer les détails de',
      'Zone',
      'Horaires',
      'Itinéraire vers',
    ],
  },
  Deutsch: {
    location: [
      'Standort wird geprüft…',
      'Sie können weiterhin allgemeine Fragen stellen, während wir auf den Gerätestandort warten.',
      'Standortzugriff abgelehnt',
      'Allgemeine Fragen funktionieren weiterhin. Aktivieren Sie den Standort im Browser für entfernungsbezogene Antworten.',
      'Erneut versuchen',
      'Standort für bessere Antworten freigeben',
      'Allgemeine Fragen funktionieren auch ohne Standort. Teilen Sie ihn, um Orte in der Nähe zu finden.',
      'Standort teilen',
    ],
    route: [
      'Route planen',
      'Start',
      'Ziel',
      'Nur als barrierefrei markierte Verbindungen verwenden',
      'Route wird gesucht…',
      'Route finden',
      'Wählen Sie zwei verschiedene Orte.',
      'Zwischen diesen Orten ist keine geprüfte barrierefreie Route verfügbar.',
      'Zwischen diesen Orten ist keine geprüfte Route verfügbar.',
      'Verwendet nur als barrierefrei markierte Verbindungen. Klären Sie wichtige Zugangsbedürfnisse mit dem Personal.',
    ],
    place: [
      'Details anzeigen für',
      'Details ausblenden für',
      'Bereich',
      'Öffnungszeiten',
      'Route zu',
    ],
  },
  Italiano: {
    location: [
      'Verifica della posizione…',
      'Puoi continuare a fare domande generali mentre attendiamo la posizione del dispositivo.',
      'Accesso alla posizione negato',
      'Le domande generali funzionano comunque. Attiva la posizione nel browser per risposte basate sulla distanza.',
      'Riprova',
      'Consenti la posizione per risposte migliori',
      'Le domande generali funzionano senza posizione. Condividila per scoprire cosa c’è nelle vicinanze.',
      'Condividi posizione',
    ],
    route: [
      'Pianifica un percorso',
      'Partenza',
      'Destinazione',
      'Usa solo collegamenti contrassegnati come accessibili',
      'Ricerca del percorso…',
      'Trova percorso',
      'Scegli due luoghi diversi.',
      'Non è disponibile un percorso accessibile verificato tra questi luoghi.',
      'Non è disponibile un percorso verificato tra questi luoghi.',
      'Usa solo collegamenti contrassegnati come accessibili. Conferma le esigenze importanti con il personale.',
    ],
    place: ['Mostra dettagli per', 'Nascondi dettagli per', 'Area', 'Orari', 'Indicazioni per'],
  },
  Português: {
    location: [
      'Verificando a localização…',
      'Você ainda pode fazer perguntas gerais enquanto aguardamos a localização do dispositivo.',
      'Acesso à localização negado',
      'As perguntas gerais continuam funcionando. Ative a localização no navegador para respostas baseadas em distância.',
      'Tentar novamente',
      'Permita a localização para respostas melhores',
      'As perguntas gerais funcionam sem ela. Compartilhe a localização para descobrir o que está por perto.',
      'Compartilhar localização',
    ],
    route: [
      'Planejar uma rota',
      'Início',
      'Destino',
      'Usar somente conexões marcadas como acessíveis',
      'Procurando rota…',
      'Encontrar rota',
      'Escolha dois locais diferentes.',
      'Não há uma rota acessível revisada entre esses locais.',
      'Não há uma rota revisada entre esses locais.',
      'Usa somente conexões marcadas como acessíveis. Confirme necessidades importantes de acesso com a equipe.',
    ],
    place: ['Mostrar detalhes de', 'Ocultar detalhes de', 'Área', 'Horários', 'Como chegar a'],
  },
  中文: {
    location: [
      '正在检查位置…',
      '等待设备位置时，您仍可询问一般问题。',
      '位置访问已拒绝',
      '一般问题仍可使用。请在浏览器设置中启用位置，以获取基于距离的回答。',
      '重试',
      '允许位置以获得更好的回答',
      '不共享位置也可询问一般问题。共享位置可了解附近地点。',
      '共享位置',
    ],
    route: [
      '规划路线',
      '起点',
      '目的地',
      '仅使用标记为无障碍的连接',
      '正在查找路线…',
      '查找路线',
      '请选择两个不同的地点。',
      '这些地点之间没有经过审核的无障碍路线。',
      '这些地点之间没有经过审核的路线。',
      '仅使用场所标记为无障碍的连接。重要的无障碍需求请向工作人员确认。',
    ],
    place: ['显示详情：', '隐藏详情：', '区域', '时间', '获取路线：'],
  },
  日本語: {
    location: [
      '位置情報を確認しています…',
      '端末の位置を待つ間も、一般的な質問はできます。',
      '位置情報へのアクセスが拒否されました',
      '一般的な質問は引き続き利用できます。距離に基づく回答には、ブラウザ設定で位置情報を有効にしてください。',
      'もう一度試す',
      'より良い回答のため位置情報を許可',
      '位置情報がなくても一般的な質問はできます。共有すると近くの場所が分かります。',
      '位置情報を共有',
    ],
    route: [
      'ルートを計画',
      '出発地',
      '目的地',
      'バリアフリーと表示された経路のみ使用',
      'ルートを検索中…',
      'ルートを検索',
      '異なる2つの場所を選んでください。',
      'この2地点間には確認済みのバリアフリールートがありません。',
      'この2地点間には確認済みのルートがありません。',
      '施設がバリアフリーと表示した経路のみを使います。重要な要件はスタッフに確認してください。',
    ],
    place: ['詳細を表示：', '詳細を隠す：', 'エリア', '時間', '道順を見る：'],
  },
  한국어: {
    location: [
      '위치 확인 중…',
      '기기 위치를 기다리는 동안에도 일반 질문을 할 수 있습니다.',
      '위치 접근이 거부됨',
      '일반 질문은 계속 사용할 수 있습니다. 거리 기반 답변을 받으려면 브라우저 설정에서 위치를 켜세요.',
      '다시 시도',
      '더 나은 답변을 위해 위치 허용',
      '위치 없이도 일반 질문은 가능합니다. 위치를 공유하면 주변 장소를 알 수 있습니다.',
      '위치 공유',
    ],
    route: [
      '경로 계획',
      '출발지',
      '목적지',
      '접근 가능으로 표시된 연결만 사용',
      '경로 찾는 중…',
      '경로 찾기',
      '서로 다른 두 장소를 선택하세요.',
      '이 장소들 사이에 검토된 접근 가능 경로가 없습니다.',
      '이 장소들 사이에 검토된 경로가 없습니다.',
      '시설이 접근 가능으로 표시한 연결만 사용합니다. 중요한 요구 사항은 직원에게 확인하세요.',
    ],
    place: ['세부 정보 보기:', '세부 정보 숨기기:', '구역', '운영 시간', '길 안내:'],
  },
  العربية: {
    location: [
      'جارٍ التحقق من الموقع…',
      'لا يزال بإمكانك طرح أسئلة عامة أثناء انتظار موقع جهازك.',
      'تم رفض الوصول إلى الموقع',
      'تظل الأسئلة العامة متاحة. فعّل الموقع في إعدادات المتصفح للحصول على إجابات تعتمد على المسافة.',
      'المحاولة مرة أخرى',
      'اسمح بالموقع للحصول على إجابات أفضل',
      'تعمل الأسئلة العامة بدونه. شارك موقعك لمعرفة ما هو قريب.',
      'مشاركة الموقع',
    ],
    route: [
      'تخطيط مسار',
      'البداية',
      'الوجهة',
      'استخدام الوصلات المحددة بأنها ميسّرة فقط',
      'جارٍ العثور على المسار…',
      'العثور على مسار',
      'اختر موقعين مختلفين.',
      'لا يوجد مسار ميسّر ومراجع بين هذين الموقعين.',
      'لا يوجد مسار مراجع بين هذين الموقعين.',
      'يستخدم فقط الوصلات المحددة بأنها ميسّرة. أكّد احتياجات الوصول المهمة مع الطاقم.',
    ],
    place: ['عرض تفاصيل', 'إخفاء تفاصيل', 'المنطقة', 'الساعات', 'الحصول على الاتجاهات إلى'],
  },
}

export function getVisitorUiCopy(language: SupportedChatLanguage = 'English') {
  return COPY[language] ?? COPY.English
}
