import assert from 'node:assert/strict'
import { readFile, readdir } from 'node:fs/promises'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const adminDirectory = path.join(repositoryRoot, 'packages/api/src/routers/admin')

const expectedAdminProcedures = [
  'acknowledgeOperationalEvent',
  'activateAgentBridgeCredential',
  'activatePlatformWorkerPolicyCredential',
  'addChatlogNote',
  'addProspectNote',
  'addSupportMessage',
  'addUniversalContentRevision',
  'admitProspectStagingPackage',
  'answerAgentQuestion',
  'appendAgentQuestionDiscussion',
  'appendEvaluationConclusion',
  'applyAgentWorkflowActivation',
  'applyAgentWorkflowTransition',
  'applyApprovedVenueLocationDraft',
  'applyFounderDecisionPacket',
  'applyNativeVenueDeployment',
  'applyVenuePackage',
  'approveNativeVenueDeployment',
  'approveProspectImport',
  'approveProspectSendBatch',
  'approveProspectStagingPackageCommit',
  'approveVenuePackage',
  'archiveProspect',
  'askFounderOperatingSystem',
  'attentionConsole',
  'authorizeGuestConversationDisposition',
  'beginProspectImport',
  'cancelCharacterFactoryJob',
  'cancelEvaluationRun',
  'cancelProspectImport',
  'claimCharacterFactoryJob',
  'compareEvaluationRuns',
  'compareNativeContentShadowRuns',
  'completeCharacterFactoryJob',
  'completeProspectImportUpload',
  'completeSupportRequest',
  'configureIntakeSourceAgentRouting',
  'configureProspectImportMapping',
  'confirmFreshnessCurrent',
  'convertPublicInterestSubmissionToProspect',
  'createAgentRoutine',
  'createAgentTask',
  'createAgentWorkflowPromotionAssessment',
  'createAndLinkIntakeCandidateDraft',
  'createAndLinkSupportReviewedVenuePackageDraft',
  'createAndLinkWebsiteMappingDraft',
  'createBillingAccessOverride',
  'createClient',
  'createClientAndVenue',
  'createClientCheckout',
  'createCompanyDecision',
  'createCompanyPriority',
  'createDisabledAgentIdentity',
  'createFileExtractionClarificationQuestion',
  'createIntakeProposal',
  'createIntakeV1PackageDraft',
  'createInterviewClarificationQuestions',
  'createKnowledgeProposal',
  'createLegacyKnowledge',
  'createLegacyKnowledgeAdoptionDraft',
  'createLegacyPlace',
  'createManualArrangement',
  'createNativeVenueDeployment',
  'createOffboardingDraft',
  'createProspect',
  'createProspectCampaign',
  'createReviewedVenuePackageDraft',
  'createSemanticConflictQuestion',
  'createSemanticOperationalUpdateDraft',
  'createSemanticUniversalContentDraft',
  'createSemanticVenueUpdatePackageDraft',
  'createSupportKnowledgeProposal',
  'createSupportLegacyKnowledgeAdoptionDraft',
  'createSupportSemanticUniversalContentDraft',
  'createUniversalContent',
  'createVenueFloorDraft',
  'createVenueLocationConnectionDraft',
  'createVenueLocationDraft',
  'createVenuePackageManifestArtifact',
  'createWebsiteResearchClarificationQuestions',
  'decideCharacterCandidateReview',
  'decideIntakeV1PackageDraftProposal',
  'decideSupportCompletionProposal',
  'decideSupportInformationRequestProposal',
  'decideSupportPackageApplicationProposal',
  'decideSupportPackageApprovalProposal',
  'decideSupportPackageDraftProposal',
  'decideSupportPackageHandoffSupersessionProposal',
  'decideSupportPackageReversionProposal',
  'decideSupportTriageProposal',
  'deleteProspectView',
  'disableAgentIdentity',
  'editDisabledAgentIdentity',
  'emergencyStopProspectDelivery',
  'enableAgentIdentity',
  'executeApprovedBillingCommand',
  'executeApprovedCustomerInvitation',
  'executeIntakeFileExtraction',
  'executeWebsiteIntakeResearch',
  'failCharacterFactoryJob',
  'finalizeOffboardingExportArtifact',
  'founderOperatingView',
  'founderUnitEconomics',
  'generateAnswerAnalysis',
  'generateWeeklyReportDraft',
  'getAdminAiSystems',
  'getAgentIdentity',
  'getAgentRun',
  'getAgentWorkflowActivationReview',
  'getAgentWorkflowTransitionComposer',
  'getAiCostBudget',
  'getAiProviderHealthControl',
  'getAnswerAnalysis',
  'getApprovalRequest',
  'getBillingRollout',
  'getClient',
  'getClientAiCosts',
  'getClientAnalytics',
  'getClientBilling',
  'getClientVenue',
  'getConversationLearningPolicy',
  'getCustomerStatePreservation',
  'getExternalCredential',
  'getFounderDecisionCurrentTruth',
  'getGlobalAiControl',
  'getGuestDesign',
  'getIntakeBuilderLifecycle',
  'getIntakeProposalReview',
  'getIntakeSourceAgentRouting',
  'getIntakeUploadDetail',
  'getIntakeVenuePackageCandidate',
  'getNativeContentConvergence',
  'getNativeGuestReadActivationPreflight',
  'getNativeVenueDeployment',
  'getOffboardingExportFinalization',
  'getOffboardingPlan',
  'getOnboardingMilestoneRollup',
  'getProspect',
  'getProspectCampaign',
  'getProspectDeliveryMessageBody',
  'getProspectImport',
  'getProspectIntelligence',
  'getProspectNoSendRehearsal',
  'getProspectOnboardingDeliveryAttempt',
  'getProspectOutreachAnalytics',
  'getProspectOutreachReadiness',
  'getProspectPipeline',
  'getSecondLayerEntitlement',
  'getSessionChatlog',
  'getSupportCompletionPreview',
  'getSupportProposalAuthoringState',
  'getSupportRequest',
  'getTochiRollout',
  'getVenueAiWorkloadConfiguration',
  'getVenueAvailability',
  'getVenueLaunchAsset',
  'getVenueLocationAuthoring',
  'getVenuePackageForReview',
  'getVenueReportConfiguration',
  'getWeeklyReport',
  'getWeeklyReportLifecycle',
  'guestChatIncidentEvidence',
  'heartbeatCharacterFactoryJob',
  'inspectCustomCharacter',
  'issueExternalCredential',
  'issueIntakeNotesProposalPolicy',
  'issueOperationalUpdateDraftPolicy',
  'issuePlatformWorkerPolicyCredential',
  'issueSupportInternalNotePolicy',
  'issueSupportRequestDraftPolicy',
  'issueSupportRequestOpenPolicy',
  'issueWeeklyReportDraftPolicy',
  'linkProspectConversion',
  'linkSupportAgentRun',
  'linkSupportDraftPackage',
  'listAgentApprovalPolicies',
  'listAgentBridgeSessions',
  'listAgentIdentities',
  'listAgentImprovementProposals',
  'listAgentOutcomeObservations',
  'listAgentQuestionDiscussion',
  'listAgentQuestions',
  'listAgentRoutines',
  'listAgentRunActions',
  'listAgentRunTimeline',
  'listAgentRunTrace',
  'listAgentRuns',
  'listAgentWorkflowActivations',
  'listAgentWorkflowPromotionAssessments',
  'listAnswerAnalyses',
  'listApprovalRequests',
  'listApprovedVenueMediaCandidates',
  'listBillingPortfolio',
  'listCharacterCandidateReviews',
  'listClients',
  'listCompanyBrain',
  'listCompatibleAgentWorkflowVersions',
  'listConversationLearningCandidates',
  'listEligibleSupportAttachments',
  'listEvaluationCases',
  'listEvaluationRuns',
  'listEvaluationSourceInsights',
  'listExternalCredentials',
  'listFreshnessAudit',
  'listGuestAnswerAttributionEvaluationRequests',
  'listGuestAnswerAttributions',
  'listGuestBrandingAssets',
  'listIntakeProposals',
  'listIntakeSourceAgentRoutingCandidates',
  'listIntakeUploads',
  'listKnowledgeProposalTemporalEvidence',
  'listKnowledgeProposals',
  'listLegacyContent',
  'listNativeContentShadowRuns',
  'listNativeVenueDeploymentEvaluationEvidence',
  'listNativeVenueDeployments',
  'listOffboardingPlans',
  'listOnboardingBootstrapDetails',
  'listOnboardingEvaluationPackages',
  'listOnboardingQuestionRecipients',
  'listPlatformWorkerPolicyCredentials',
  'listProductEntitlements',
  'listProspectActivities',
  'listProspectCampaignDeliveries',
  'listProspectCampaignMembers',
  'listProspectCampaigns',
  'listProspectDuplicates',
  'listProspectImports',
  'listProspectSavedViews',
  'listProspectTerritories',
  'listProspectThreadMessages',
  'listProspectThreads',
  'listProspects',
  'listPublicInterestSubmissions',
  'listRejectedConversationCandidates',
  'listSupportAgentRunLineages',
  'listSupportAuditEvents',
  'listSupportDraftPackages',
  'listSupportKnowledgeProposals',
  'listSupportMessages',
  'listSupportPackageHandoffs',
  'listSupportRequests',
  'listUniversalContent',
  'listVenuePackagesForReview',
  'listVenueSessions',
  'listWebsitePageText',
  'listWeeklyReports',
  'markFounderBriefingReviewed',
  'operationsReadiness',
  'overview',
  'ping',
  'prepareAgentImprovementProposal',
  'prepareCharacterFactoryJob',
  'prepareConversationEvaluationCase',
  'prepareGuestAnswerAttributionEvaluation',
  'prepareLegacyKnowledgeAdoptionDraft',
  'prepareOnboardingEvaluationSuite',
  'prepareProspectEmailAttachmentRetention',
  'prepareSupportPortableExport',
  'previewCurrentEvaluationSourceCoverage',
  'previewFullVenueDeploymentManifest',
  'previewGuestAnswerAttributionAgreement',
  'previewIntakeV1Package',
  'previewOffboardingExportManifest',
  'previewProspectImportRepair',
  'previewRetentionDisposition',
  'previewSemanticVenueUpdate',
  'previewTerminalJobRedrive',
  'previewUniversalContent',
  'previewWebsiteVenuePackageMapping',
  'projectNativeVenueDeployment',
  'promoteAgentAnswer',
  'promoteAgentAnswerToFounderDecision',
  'publishUniversalContent',
  'publishWeeklyReport',
  'queueCompanyMeetingProcessing',
  'queueGuestAnswerAttributionEvaluation',
  'queueProspectSendBatch',
  'readCharacterCandidatePreview',
  'readIntakeFileExtractionSource',
  'readWebsitePageText',
  'recheckProspectFollowup',
  'reconcileClientAndVenue',
  'reconcileClientBilling',
  'recordAgentImprovementValidation',
  'recordAgentRunOutcome',
  'recordAgentTrustSignal',
  'recordApprovalDecision',
  'recordHumanReviewedGuestAnswerAttribution',
  'recordManualPayment',
  'recordNativeVenueDeploymentEvaluationEvidence',
  'recordOperatingCostEvidence',
  'recordReleaseEvidence',
  'recordSupportReviewedDecline',
  'registerAgentWorkflowVersion',
  'registerVenueMediaAsset',
  'releaseEvidence',
  'repairProspectImport',
  'requestAgentRunCancellation',
  'requestAgentWorkflowActivationApproval',
  'requestAgentWorkflowTransitionApproval',
  'requestEvaluationRun',
  'requestNativeVenueDeploymentEvaluation',
  'requestSupportInformation',
  'requestVenueMediaDerivatives',
  'reserveProspectImportUpload',
  'resetAiCostBudgetWindow',
  'resetAiWorkloadConfigurationOverride',
  'resolveFileExtractionClarification',
  'resolveInterviewClarification',
  'resolveOperationalEvent',
  'resolveProspectDuplicate',
  'resolveProspectImportRow',
  'resolveSemanticConflict',
  'resolveSupportSemanticDuplicate',
  'retireLegacyKnowledge',
  'retireLegacyPlace',
  'retireUniversalContent',
  'retryProspectImportJob',
  'revertNativeVenueDeployment',
  'revertVenuePackage',
  'reviewConversationLearningCandidate',
  'reviewDeploymentManifest',
  'reviewIntakeFileExtraction',
  'reviewIntakeSourceMapping',
  'reviewKnowledgeProposal',
  'reviewOffboardingPlanExports',
  'reviewProspectContactReadiness',
  'reviewProspectEmailAttachmentRetention',
  'reviewProspectInboundReply',
  'reviewProspectOutreachDraft',
  'reviewPublicInterestSubmission',
  'reviewVenueMediaAsset',
  'revokeAgentApprovalPolicy',
  'revokeAgentBridgeSession',
  'revokeExternalCredential',
  'revokePlatformWorkerPolicyCredential',
  'rotateExternalCredential',
  'routeAgentQuestionToClient',
  'saveAiWorkloadConfigurationOverride',
  'saveProspectOutreachDraft',
  'saveProspectView',
  'scanProspectDuplicates',
  'scheduleProspectFollowup',
  'searchAdminOs',
  'searchClients',
  'setAgentRoutineEnabled',
  'setAiCostBudget',
  'setAiProviderHealthOverride',
  'setBillingTenantFlag',
  'setEvaluationRuntimeDurableGates',
  'setGlobalAiControl',
  'setProductEntitlementOverride',
  'setProductPlanCapability',
  'setSecondLayerEntitlement',
  'setSessionNotable',
  'setTenantPaymentDue',
  'setTochiTenantFlag',
  'setVenueAvailability',
  'setVenueFloorAvailability',
  'setVenueLocationAvailability',
  'setVenueLocationConnectionAvailability',
  'stageProspectImportRows',
  'stageProspectSendBatch',
  'submitCharacterCandidateReview',
  'transitionSupportRequestStatus',
  'triageSupportRequest',
  'triggerDigest',
  'updateClientPlanTier',
  'updateClientStatus',
  'updateConversationLearningPolicy',
  'updateGuestDesign',
  'updateLegacyKnowledge',
  'updateLegacyPlace',
  'updateProspectPipeline',
  'updateVenueFloorDraft',
  'updateVenueLocationConnectionDraft',
  'updateVenueLocationDraft',
  'updateVenueReportConfiguration',
  'updateWeeklyReportDraft',
  'visitorFeedbackHazardEvidence',
  'withdrawUniversalContent',
]

const expectedMediaProcedures = [
  'abortUpload',
  'applyReviewedRelationDraft',
  'beginUpload',
  'completeUpload',
  'create',
  'createIntakeHandoff',
  'createTemporalClarification',
  'createTemporalOperationalDraft',
  'createTemporalReceiptClarification',
  'expireAbandonedUploads',
  'get',
  'getIdentityReview',
  'getIntakeHandoff',
  'list',
  'listAssets',
  'listFindings',
  'previewIdentityCandidates',
  'previewIntakeHandoff',
  'previewTemporalReview',
  'readIdentityEvidence',
  'readIntakeHandoffEvidence',
  'readTemporalReviewEvidence',
  'reconcileUpload',
  'retainTemporalReview',
  'retryEnqueue',
  'saveIdentityReview',
  'saveReview',
  'signPart',
  'status',
]

function procedureNames(source) {
  return [...source.matchAll(/^ {2}([a-zA-Z][a-zA-Z0-9]+): admin(?:Ai)?Procedure/gmu)].map(
    (match) => match[1],
  )
}

test('platform-admin routers stay domain-split without changing their public procedure inventory', async () => {
  const entries = await readdir(adminDirectory, { withFileTypes: true })
  const productionRouterFiles = entries
    .filter(
      (entry) => entry.isFile() && entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts'),
    )
    .map((entry) => entry.name)

  const adminProcedures = []
  const mediaProcedures = []

  for (const fileName of productionRouterFiles) {
    const source = await readFile(path.join(adminDirectory, fileName), 'utf8')
    const lineCount = source.split(/\r?\n/u).length - 1
    assert.ok(lineCount <= 400, `${fileName} has ${lineCount} lines; split it by domain`)

    const target = fileName.startsWith('media-ingestion-') ? mediaProcedures : adminProcedures
    target.push(...procedureNames(source))
  }

  const sortedAdminProcedures = adminProcedures.sort()
  const sortedMediaProcedures = mediaProcedures.sort()

  assert.equal(
    new Set(sortedAdminProcedures).size,
    sortedAdminProcedures.length,
    'admin procedure names must not be mounted by more than one router',
  )
  assert.equal(
    new Set(sortedMediaProcedures).size,
    sortedMediaProcedures.length,
    'media procedure names must not be mounted by more than one router',
  )
  assert.deepEqual(sortedAdminProcedures, expectedAdminProcedures)
  assert.deepEqual(sortedMediaProcedures, expectedMediaProcedures)

  for (const composer of ['_admin.ts', 'media-ingestion.ts']) {
    const source = await readFile(path.join(adminDirectory, composer), 'utf8')
    assert.match(source, /mergeRouters\(/u, `${composer} must compose its domain routers`)
    assert.equal(procedureNames(source).length, 0, `${composer} must not regain inline procedures`)
  }
})

test('intake exposes no arbitrary existing-draft link procedure', async () => {
  const sources = await Promise.all([
    readFile(path.join(repositoryRoot, 'packages/api/src/routers/intake.ts'), 'utf8'),
    readFile(path.join(adminDirectory, 'intake-operations.ts'), 'utf8'),
  ])
  for (const source of sources) {
    assert.doesNotMatch(source, /\blinkPackageDraft\s*:/u)
    assert.doesNotMatch(source, /\blinkIntakePackageDraft\s*:/u)
  }
})
